(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.mobileleaderboardtable = function() {
	this.initialize(img.mobileleaderboardtable);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,50);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.somethingdeliciousmobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgHA0IgKgBIgEABIgDABIgCAAIgCgBQgDgEgDgHQgDgJAAgIQAAgCACgDQAAAAABgBQAAAAAAAAQABgBABAAQAAAAABAAQAFAAAEAIIAEAHQADAEAGACQAFACAFAAQAHAAAEgDQAEgDAAgHQAAgIgRgIIgFgDQgQgIgGgFQgFgHAAgJQAAgOAJgJQAJgHAPgBIAGAAIAHACIAFgCIADgBQAFABAFAHQAFAIAAAJQAAAEgCACQgBAAAAABQAAAAgBAAQAAABgBAAQgBAAAAAAQgDAAgCgCIgFgHQgEgGgEgDQgEgCgGAAQgFAAgEADQgDADAAAGQAAAEADAEQAEAEAMAGIABAAQAcAOAAAQQAAAOgKAKQgLAJgRAAg");
	this.shape.setTransform(127.4,-5.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AAWA0IgBgGIAAgHIAAAAIgBAAQAAAAAAAAQgBAAAAABQgBAAAAAAQgBABgBAAIAAACQgFAFgGACQgGADgIAAQgHAAgGgDQgIgDgEgGQgFgFgBgIQgDgJAAgUIAAgHIAAgIIAAgCQAAgIgBgCQgBgDgDgBIgFgCQgFgBAAgEQAAAAAAgBQAAAAAAgBQAAAAABgBQAAgBABAAIAJgEIANgEIAMgBQAAAAABAAQABAAAAAAQABABAAAAQAAABAAAAIABAHIAAADIgBAnQABATAEAIQAEAIAKAAQALAAAFgLQAFgKABgXIAAgIQAAgIgCgCQgBgDgDgBIgFgCQgFgBAAgEQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABgBQACgCAHgCIAOgEIAKgBQABAAAAAAQABAAABAAQAAABABAAQAAAAAAAAIABAIIAAAFIgBApIAAARIABAHQABAEAFACIACABQAFABABAEQAAABgBAAQAAABAAAAQAAABAAAAQgBABAAAAQgCACgEABIgPAGIgLABQAAAAgBAAQgBAAAAAAQgBgBAAAAQgBAAAAAAg");
	this.shape_1.setTransform(116.7,-5.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AgkAmQgPgPAAgXQAAgWAQgPQAPgPAWAAQAWAAAOAOQAOAOAAAXQAAAWgPAQQgQAQgVAAQgWAAgOgPgAgTgeQgGAIAAAOQAAAUAJANQAIANAMAAQAKAAAGgIQAGgIAAgOQAAgTgJgOQgIgNgLAAQgKAAgHAIg");
	this.shape_2.setTransform(104.9,-5.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AgRBJQgFgCgBgFQAAgDAGgCIADgBQACgBABgEIABgLIAAgHIAAgIIAAgLQAAgQgBgDQgBgFgCgBIgEgCQgHgCABgEQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBIAHgDIAPgFIAKgCQAAAAABAAQABAAAAABQAAAAABAAQAAAAAAABQACACAAAFIAAAGIgBAEIAAAZIAAABIgBAZIABAOQABAEADABIADABQAFACABAEQgBAEgFACQgEABgOAAQgOAAgFgBgAgMgyQgEgEAAgFQAAgGAEgEQAGgEAGAAQAGAAAFADQADAEAAAGQABAFgFAEQgFAEgGAAQgGAAgFgDg");
	this.shape_3.setTransform(96.1,-7.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AgfAmQgPgPAAgWQAAgWAQgPQAPgQAWAAQAQAAAMAJQAMAJAAALQAAAFgDACQgEADgFAAQgFAAgDgCQgDgDgEgHQgDgIgEgCQgEgDgGgBQgLAAgGAJQgHAJAAAPQAAARAJAMQAKAMANAAIAKgCQAFgBADgDIAEgCQAGgFADAAIADABIABAEQAAACgCADQgCAEgDADQgIAHgJADQgIAEgLAAQgUAAgOgPg");
	this.shape_4.setTransform(87.8,-5.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AgRBJQgGgCABgFQAAgDAEgCIAEgBQACgBABgEIABgLIAAgHIAAgIIAAgLQAAgQgBgDQgBgFgBgBIgGgCQgFgCgBgEQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAABgBIAFgDIAQgFIAJgCQABAAABAAQAAAAABABQABAAAAAAQAAAAABABQABACAAAFIAAAGIAAAEIgBAZIAAABIAAAZIABAOQABAEABABIAFABQAEACAAAEQAAAEgEACQgGABgMAAQgQAAgEgBgAgMgyQgEgEAAgFQAAgGAFgEQAFgEAGAAQAGAAAEADQAFAEAAAGQgBAFgEAEQgFAEgGAAQgGAAgFgDg");
	this.shape_5.setTransform(79.5,-7.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AgRBJQgEgCAAgEQgBgDAFgCIAFgDQABgCACgGIAAgUIAAgQIAAgSIAAgIQAAgZgBgIQgBgHgCgBIgGgDQgGgBgBgEQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBAAAAIAJgEIAPgEIAJgCQABAAAAAAQABABABAAQAAAAAAAAQABABAAAAQACACAAAFIgBAIIgBBIIABAjQABAHABACIAFADQAGACgBAEQABAEgGABQgEACgOAAQgPAAgFgCg");
	this.shape_6.setTransform(73.4,-7.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AggAmQgPgPAAgWQAAgXAPgPQAPgPAWAAQAUAAALALQAMALAAATQAAAGgCACQgCADgIAAIgmAAQgDAAgCgCQAAAAgBgBQAAgBAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQACgCADAAIAVAAIAFgBQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAgBQAAgKgGgHQgHgGgJAAQgMAAgGALQgGAKAAAPQAAAPAJALQAIAMAMAAQAHAAAFgBQAGgDAEgDIAEgCQAFgFADAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABQAAACgCAEIgHAHQgJAHgIADQgIAEgKAAQgVAAgOgPg");
	this.shape_7.setTransform(65.2,-5.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AgVBJIgNAAIgIAAIgJAAQgMAAgEgCQgEgBAAgEQAAgEAFgCQAGgDABgBQABgCABgPIABgnIgBgmQgBgPgBgCQgBgCgGgBQgFgCAAgFQAAgEAEgCQAFgBAMAAIAIAAIALAAIANAAIAMgBQAlAAAVAUQAUATAAAkQAAAjgVASQgVATgogBgAgVg5QgFABgBAEQgCADAAAMIgBAgIABAmIACASQABADAGADQAHACAKAAQAWAAAMgOQALgOAAgcQAAgegNgQQgNgPgZAAQgIAAgEABg");
	this.shape_8.setTransform(51.7,-7.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("AglBDQgNgIAAgMQAAgFADgDQACgDAGAAQAEAAADACQACACABAFQADAIAGAEQAHAEAMAAQANAAAJgFQAJgFAAgIQAAgFgEgCQgDgDgGAAIgMABIgPABQgSAAgKgHQgKgGAAgIQAAgFAEgFQADgEAIgEQgGgFgDgHQgDgGAAgIQAAgRAMgLQANgLATAAIAKABIAPADQAEAAAFgCIAKgGIAEADIABADQAAAFgDAEQgEAEgGADIAEAIIABAIQAAARgNALQgMAJgTAAIgLAAIgKgCIgDAEIgBADQAAAFAFACQAFADAKAAIAPgBIAPgCQAPAAAHAGQAIAGAAALQAAAQgQALQgQAKgYAAQgTAAgNgHgAgQgyQgFAHAAAKQAAALAFAGQAFAGAIAAQAIAAAGgGQAFgHAAgKQAAgKgFgHQgGgGgIAAQgIAAgFAGg");
	this.shape_9.setTransform(33.1,-3.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006F46").s().p("AAOAyQgFgBgBgEQABgEAFgCIADgBQADgCABgEIABgQQAAgfgFgJQgEgIgKAAQgFAAgEADQgGAEgCAFQgCAFgCAIIgBAbIABANQACADACACIADABQAFACABAEQgBAEgFABQgEACgOAAQgPAAgFgCQgFgCgBgEQAAgDAGgCIACgBQADgCABgDIABgLIAAgHIAAgIIAAgKQAAgQgBgFQgBgEgCgCIgEgCQgHgCABgDQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBIAHgDIAOgFIALgCQAAAAABAAQABAAAAAAQABABAAAAQABAAAAAAIABAGIAAAGIAAACIABAAIAAAAIABgBIACgCIACgCQAMgKAMAAQAHAAAGADQAHADAFAFQAEAGACAIQACAIAAAQIAAANIAAAHIAAAFIACAKQABAEACABIACABQAGACAAADQgBAEgEACQgFACgQAAQgOAAgEgCg");
	this.shape_10.setTransform(21.1,-5.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006F46").s().p("AgRBJQgFgCgBgFQAAgDAGgCIACgBQADgBABgEIABgLIAAgHIAAgIIAAgLQAAgQgBgDQgBgFgCgBIgEgCQgHgCABgEQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBIAHgDIAPgFIAKgCQAAAAABAAQABAAAAABQAAAAABAAQAAAAAAABQACACAAAFIAAAGIgBAEIAAAZIAAABIgBAZIABAOQABAEADABIADABQAFACABAEQgBAEgFACQgEABgOAAQgOAAgFgBgAgMgyQgEgEAAgFQAAgGAEgEQAGgEAGAAQAGAAAFADQADAEAAAGQABAFgFAEQgFAEgGAAQgGAAgFgDg");
	this.shape_11.setTransform(11.9,-7.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006F46").s().p("AAOBJQgFgBAAgFQAAgDAFgCIAEgCQADgBAAgEIABgQQAAgggEgIQgEgIgLAAQgFAAgEADQgFAEgDAEQgCAFgBAHIgBAcIABAOQABADACABIAEACQAFACAAADQAAAFgFABQgFABgNABQgQgBgFgBQgFgCAAgFQAAgCAFgCIADgCQACgBABgEQACgFAAgLIAAgRIAAgPIgBguQAAgKgCgCQgBgCgGgBQgGgDAAgDQAAgCADgDIALgFIAKgCIAJgCQAEAAACACIABAGIAAAFIgBAoIAAAGIAAACIABAAIADgCIAEgDQAEgGAGgCQAFgDAGAAQASAAAIAMQAJALAAAWIAAAKIAAASIAAAFIABAHQABADADABIACACQAFABAAADQAAAFgFACQgFABgQABQgNgBgFgBg");
	this.shape_12.setTransform(2.7,-7.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006F46").s().p("AgFA9QgEgBgEgEQgEgDgBgGQgCgFAAgPIAAg2IgJAAIgDgBIgBgDIAAgCQAAgEALgIIAEgEIAEgDQAKgKAEAAIACABIABACIAAATIAYAAIADABIABAFIAAACIgBADQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgWAAIgBABIgBACIAAAyQAAANACADQACADAGABQAEAAAFgCIAHgCQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAGgIAEQgJAGgLAAQgGAAgFgCg");
	this.shape_13.setTransform(-7,-6.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006F46").s().p("AggAmQgPgPAAgWQAAgXAPgPQAPgPAWAAQAUAAALALQAMALAAATQAAAGgCACQgCADgIAAIgmAAQgDAAgCgCQAAAAgBgBQAAgBAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQACgCADAAIAVAAIAFgBQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAgBQAAgKgGgHQgHgGgJAAQgMAAgGALQgGAKAAAPQAAAPAJALQAIAMAMAAQAHAAAFgBQAGgDAEgDIAEgCQAFgFADAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABQAAACgCAEIgHAHQgJAHgIADQgIAEgKAAQgVAAgOgPg");
	this.shape_14.setTransform(-16.2,-5.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006F46").s().p("AAtAyQgFgBAAgEQAAgEAFgCIAEgCQADgBAAgFIABgRQAAgdgDgJQgEgIgMAAQgLAAgFALQgGAKABAYIAAAGQgBALACADQABADACACIADABQAFACAAADQAAAEgEACQgGACgPAAQgNAAgFgCQgFgBAAgEQAAgEAFgCIAEgBQACgCABgEIABgQQAAgfgEgJQgEgIgLAAQgFAAgFADQgFAEgDAFQgCAFgBAJIgBAaIABAMQABAEACACIAEABQAFACAAAEQAAAEgFABQgFACgOAAQgPAAgFgCQgEgCAAgEQAAgDAEgCIADgBQACgCACgDIAAgLIAAgHIAAgIIAAgGQAAgSAAgGQgBgFgCgCIgFgCQgGgCAAgDQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABgBIAGgDIAPgGIAKgBQABAAAAAAQABAAABAAQAAABAAAAQABAAAAAAQACACAAAEIAAAFIAAABIAAACIABAAIAAAAIABgBIACgCIABgBQAMgLAMAAIAKABIAIAFIAHAGIAEAFQACAAADgDIAEgFQAHgFAFgCQAEgCAHAAQAMAAAIAEQAJAGAEAIQAEAJAAAdIAAAKIAAAFIAAAGIABAIQACACACACIADABQAFACAAADQAAAEgFACQgEACgQAAQgPAAgFgCg");
	this.shape_15.setTransform(-31.1,-5.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006F46").s().p("AgkAmQgPgPAAgXQAAgWAQgPQAPgPAWAAQAWAAAOAOQAOAOAAAXQAAAWgPAQQgQAQgVAAQgWAAgOgPgAgTgeQgGAIAAAOQAAAUAJANQAIANAMAAQAKAAAGgIQAGgIAAgOQAAgTgJgOQgIgNgLAAQgKAAgHAIg");
	this.shape_16.setTransform(-46.3,-5.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006F46").s().p("AgYBJQgMgCgHgFQgEgCgDgJQgCgIAAgMQAAgEACgDQABgCAEAAQAEAAAFAJIADAEQAGALAIAGQAIAFAKAAQALAAAHgHQAIgGAAgKQAAgOgegOIgDgBQgYgKgIgJQgJgJAAgOQAAgSAOgMQANgMAWAAIALABIAOADIAEgCIAEgBQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAIAEAGQAEAGACAHQACAGAAAFQAAAEgCACQAAAAgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAQgGAAgFgHIgBgCQgGgHgHgEQgHgEgIAAQgLAAgGAGQgHAFAAAJQAAAIAGAGQAFAGAVAJIAEACQATAHAIAHQAFAFADAHQADAHAAAIQAAAUgOAMQgPAMgZAAQgMAAgLgDg");
	this.shape_17.setTransform(-58.1,-7.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.somethingdeliciousmobileleaderboard, new cjs.Rectangle(-66.1,-21.5,200.2,28.2), null);


(lib.signupmobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgUA0QgJgEgGgHIAMgKQADAFAHAEQAGADAHAAIAHgBQAEgBADgCQACgCACgEQADgDAAgFQAAgFgDgDQgBgDgEgCIgIgEIgIgEIgKgDQgGgBgDgEQgFgDgCgFQgCgFAAgHQAAgIADgGQADgGAFgDQAFgEAHgCQAGgCAHAAIAJABIAIADQAIADAEAFIgKALQgDgFgGgCQgFgDgGAAIgHABIgHADIgEAFQgCAEAAAEQAAAEACADIAEAFIAHAEIAIADIAKADIAKAFQAFADADAGQADAFAAAIQAAAIgEAGQgDAGgFAEQgFAEgGACQgHACgGAAQgKAAgKgEg");
	this.shape.setTransform(-41.5,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgeA1IAAhpIAPAAIAABcIAuAAIAAANg");
	this.shape_1.setTransform(-49.1,-0.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgGA1IAAhpIANAAIAABpg");
	this.shape_2.setTransform(-55.7,-0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAkA1IgLgaIgxAAIgLAaIgRAAIAvhpIAMAAIAuBpgAAUAOIgUgxIgTAxIAnAAg");
	this.shape_3.setTransform(-63.3,-0.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAoA1IAAhYIgkBYIgIAAIgjhYIAABYIgPAAIAAhpIAXAAIAfBRIAghRIAXAAIAABpg");
	this.shape_4.setTransform(-75.5,-0.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgiA1IAAhpIBDAAIAAANIg0AAIAAAfIAxAAIAAANIgxAAIAAAjIA2AAIAAANg");
	this.shape_5.setTransform(-86.7,-0.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAUA1IgagvIgQAAIAAAvIgPAAIAAhpIAiAAQAHAAAHACQAHABAFADQAFAEADAFQADAGAAAIQAAAMgHAHIgIAFQgFACgGABIAeAxgAgWgFIARAAIAJgBIAIgEQADgCACgDQACgDAAgFQAAgEgCgEQgCgDgDgCIgIgDIgIAAIgSAAg");
	this.shape_6.setTransform(-99.8,-0.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgLA3IgLgDQgKgEgHgIQgIgHgEgKQgEgLAAgMQAAgLAEgLQAEgKAIgHQAHgIAKgEIALgDIALgBQAMAAAKAEQAGACAEADIAIAHQAIAHAEAKQAEALAAALQAAAMgEALQgEAKgIAHQgEAEgEADQgEADgGACQgKAEgMAAIgLgBgAgQgmQgHADgFAGQgGAGgCAIQgDAHAAAIQAAAJADAIQACAHAGAGQAFAGAHADQAIAEAIAAQAJAAAIgEQAHgDAFgGQAFgGADgHQADgIAAgJQAAgIgDgHQgDgIgFgGQgFgGgHgDQgIgEgJAAQgIAAgIAEg");
	this.shape_7.setTransform(-111.4,-0.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AggA1IAAhpIBBAAIAAANIgyAAIAAAhIAvAAIAAALIgvAAIAAAwg");
	this.shape_8.setTransform(-121.8,-0.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgiA1IAAhpIAgAAQAIAAAHACQAHABAFAEQAFADACAGQADAFAAAJQAAAHgDAGQgDAFgFAEQgFADgHACQgHABgIAAIgQAAIAAAvgAgTgFIAPAAIAJgBIAIgDIAFgFQACgEAAgEQAAgGgCgCQgCgEgDgCIgIgDIgIAAIgQAAg");
	this.shape_9.setTransform(-134.7,-0.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgJA2IgIgDIgHgEIgGgFQgFgGgDgIQgCgHAAgJIAAhBIAPAAIAABBIABAKQABAGADAEQAEAEAFADQAFACAGAAQAHAAAGgCQAFgDADgEQADgEABgGIACgKIAAhBIAOAAIAABBQAAAJgCAHQgDAIgFAGIgFAFIgIAEIgIADIgKAAIgJAAg");
	this.shape_10.setTransform(-145,-0.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAaA1Ig3hVIAABVIgPAAIAAhpIATAAIA2BUIABAAIAAhUIAPAAIAABpg");
	this.shape_11.setTransform(-160.2,-0.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgNA0QgLgEgHgIQgIgHgEgKQgEgLAAgMQAAgLAEgLQAEgKAIgHIAIgHIAKgFQAKgEALAAIAMABIALADQAKAEAHAGIgLALQgFgFgHgDIgIgDIgJgBQgIAAgHAEQgIADgFAGQgFAGgDAIQgDAHAAAIQAAAJADAIQADAHAFAGQAFAGAIADQAHAEAJAAQAHAAAHgCIALgEIAAgdIgYAAIAAgMIAmAAIAAAzQgIAEgKADIgWACQgLAAgKgEg");
	this.shape_12.setTransform(-172.3,-0.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgGA1IAAhpIANAAIAABpg");
	this.shape_13.setTransform(-180.1,-0.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgTA0QgKgEgGgHIALgKQAFAFAFAEQAHADAHAAIAHgBQAEgBADgCQADgCABgEQACgDAAgFQAAgFgCgDQgCgDgDgCIgIgEIgIgEIgLgDQgEgBgFgEQgEgDgCgFQgCgFAAgHQAAgIADgGQADgGAGgDQAEgEAHgCQAGgCAHAAIAJABIAHADQAJADAFAFIgLALQgDgFgFgCQgGgDgHAAIgGABIgGADIgGAFQgBAEAAAEQAAAEABADIAFAFIAHAEIAIADIALADIAKAFQAEADADAGQADAFAAAIQAAAIgDAGQgEAGgEAEQgGAEgHACQgGACgGAAQgKAAgJgEg");
	this.shape_14.setTransform(-186.7,-0.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.signupmobileleaderboard, new cjs.Rectangle(-193,-11.9,158.2,22.4), null);


(lib.partyreadyrecipesmobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgHA1IgKgCIgEACIgDABIgCgBIgCgBQgDgEgDgIQgDgIAAgHQAAgEACgCQAAAAABgBQAAAAAAAAQABgBABAAQAAAAABAAQAFAAAEAJIAEAFQADAEAGADQAFACAFAAQAHAAAEgDQAEgEAAgFQAAgJgRgIIgFgDQgQgIgGgGQgFgGAAgKQAAgNAJgIQAJgJAPAAIAGAAIAHACIAFgCIADAAQAFgBAFAJQAFAHAAAKQAAADgCACQgBABAAAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgDAAgCgCIgFgHQgEgGgEgCQgEgDgGAAQgFAAgEADQgDADAAAGQAAAEADAEQAEAEAMAGIABABQAcAMAAARQAAAPgKAJQgLAKgRAAg");
	this.shape.setTransform(127.2,-5.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AggAmQgPgPAAgVQAAgXAPgQQAPgPAWAAQAUAAALALQAMALAAATQAAAGgCACQgCACgIAAIgmAAQgDABgCgCQAAAAgBgBQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBQAAgBABAAQAAgBAAAAQABAAAAgBQACgBADAAIAVAAIAFgBQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAgBQAAgKgGgGQgHgHgJAAQgMAAgGAKQgGALAAAPQAAAPAJALQAIAMAMAAQAHAAAFgCQAGgCAEgDIAEgDQAFgEADAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAACgCAEIgHAHQgJAIgIADQgIADgKAAQgVAAgOgPg");
	this.shape_1.setTransform(117.4,-5.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AgxBFQgFgCAAgEQAAgDAFgCIAFgCQACgDABgIIAAghIAAgPQAAgdgBgHQAAgJgDAAIgFgCQgGgCAAgEQAAAAAAgBQAAgBABAAQAAgBAAAAQABgBAAAAIAGgDIAPgFIAKgBQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABACAAADIAAAFIAAACIABAAIAEgCIAEgDQAGgFAFgCQAGgCAGAAQASAAANANQAMAOAAAWQAAAYgOAPQgOARgUgBQgJABgCgDQgEgCAAgFQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABgBQAAAAABAAQABAAAAAAIACABIAEAAQALAAAHgJQAHgKAAgPQAAgRgIgLQgHgLgMABQgJAAgHAFQgGAGAAAQIAABAIABAKQAAADACACQABACAFABIAEABIACACIABADQAAADgGACQgGACgPAAQgPAAgFgCg");
	this.shape_2.setTransform(105.5,-3.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AgRBJQgGgCAAgFQABgDAFgCIACgBQADgBABgEIABgLIAAgHIAAgIIAAgLQAAgQgBgDQgBgFgCgBIgEgCQgHgCAAgEQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAgBIAGgDIAQgFIAKgCQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQACACAAAFIAAAGIgBAEIAAAZIAAABIgBAZIABAOQACAEACABIADABQAGACAAAEQAAAEgGACQgEABgOAAQgOAAgFgBgAgMgyQgEgEAAgFQAAgGAFgEQAEgEAHAAQAGAAAEADQAEAEABAGQAAAFgFAEQgFAEgGAAQgGAAgFgDg");
	this.shape_3.setTransform(96.7,-7.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AgfAmQgPgPAAgVQAAgXAQgQQAPgPAWAAQAQAAAMAIQAMAJAAAMQAAAFgDADQgEADgFAAQgFgBgDgCQgDgCgEgJQgDgHgEgDQgEgDgGAAQgLABgGAIQgHAJAAAQQAAARAJALQAKALANAAIAKgBQAFgBADgDIAEgDQAGgEADAAIADABIABADQAAADgCADQgCAEgDADQgIAHgJAEQgIADgLAAQgUAAgOgPg");
	this.shape_4.setTransform(88.5,-5.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AggAmQgPgPAAgVQAAgXAPgQQAPgPAWAAQAUAAALALQAMALAAATQAAAGgCACQgCACgIAAIgmAAQgDABgCgCQAAAAgBgBQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBQAAgBABAAQAAgBAAAAQABAAAAgBQACgBADAAIAVAAIAFgBQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAgBQAAgKgGgGQgHgHgJAAQgMAAgGAKQgGALAAAPQAAAPAJALQAIAMAMAAQAHAAAFgCQAGgCAEgDIAEgDQAFgEADAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAACgCAEIgHAHQgJAIgIADQgIADgKAAQgVAAgOgPg");
	this.shape_5.setTransform(77.7,-5.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AAWAzQgKgggHgHQgGgGgLgBQgIABAAgHQAAgFAHAAQAQAAAIgHQAIgHAAgNQAAgOgIgHQgIgHgPABIgLABQgDABgBACIgBAJIAAAUIAAAtIAAAfQABAGACACIAEACQAHADAAAEQAAAEgGABQgGACgQABQgQgBgFgCQgGgBAAgEQAAgEAGgDIAFgCQACgCABgMIABgsIgBgmQgBgPgBgCQgBgBgGgCQgFgCAAgEQAAgEADgCQADgCAHAAIAWAAIAUAAIAQgBQAWAAAMAKQALAKAAARQAAAOgHAKQgIAKgOADIAAACQALACAGAGQAGAGAFARIADAKQAEAQAGAAIACAAIAEAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAAEgGADQgFAEgKAAQgUgBgHgXg");
	this.shape_6.setTransform(65.1,-7.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AguBDQgFgEAAgGQAAgGADgDQAEgEAFAAIAFABIADACIACAEQAEAEABAAQAFAAAGgHQAFgIAAgIQAAgJgHgQIgBgCIgQgjIgKgUQgBgDgHgDIAAAAQgDgBgBgCQAAAAgBgBQAAAAAAAAQAAgBAAAAQgBgBAAAAQAAgFAGgCQAGgBAOAAQAPAAAFABQAFACAAAEIgBADIgBACIgEACQgEABAAACIACAIIAIAUIAHATQADAFABAAQACAAACgFIAHgQIAHgUIADgKQAAgDgGgDQgGgDAAgDQAAgDAFgCQAFgBALAAQAMAAAFABQADACABAEQgBAEgFABIgEACQgGADgGARIgEAIIgMAgQgRAqgKANQgLAMgOAAQgIAAgFgEg");
	this.shape_7.setTransform(46.6,-3.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AAUBJQgBgBAAgEIAAgEIAAgCIgBgBIgDACIgFADQgGAFgEACQgGACgHAAQgTAAgMgNQgMgOAAgWQAAgZAOgPQAOgPAWAAIAGABQADABACACQABAAAAABQAAABAAAAQABABAAAAQAAABAAAAQAAAGgHAAIgCAAIgDgBQgLAAgHAKQgHAIAAAQQAAASAIAKQAHALAMAAQAJAAAGgGQAGgGAAgLIAAgcIAAguQAAgIgBgCQgBgDgEgBIgDgBQgGgCAAgEQAAgCACgCIAKgFIAMgDIAJgBQAEAAABACQACACAAAEIAAAFIgCA+IABArQABAJABACIAHACQAGACAAADQAAAFgPAFIgKACIgIABQAAAAgBAAQgBAAAAAAQgBgBAAAAQgBAAAAgBg");
	this.shape_8.setTransform(35.5,-7.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("AASAwIgFgGIgFACQgMAJgMAAQgPAAgJgJQgJgIAAgOQAAgQALgJQAMgJAVAAQAFAAACACQADABAAAEQAAAFgGAAQgKAAgGAFQgHAFAAAIQAAAJAGAFQAFAEAJAAQAJABAEgFQAEgEAAgLIAAgmQAAgJgDgFQgEgEgHAAQgFgBgEADQgEACgEAFIgCACQgGAIgHAAQgEAAgDgCQgCgDAAgFQAAgJAMgHQALgGATAAQAKAAAIADQAJADAEAGQADADABAHQACAGAAAOIAAAgIABAJQAAABAAAAQABABAAAAQAAAAABABQAAAAABAAIADABQAGACAAADQAAAFgHAEQgGAEgKAAQgEAAgFgFg");
	this.shape_9.setTransform(23.7,-5.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006F46").s().p("AggAmQgPgPAAgVQAAgXAPgQQAPgPAWAAQAUAAALALQAMALAAATQAAAGgCACQgCACgIAAIgmAAQgDABgCgCQAAAAgBgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQABgBAAAAQAAgBAAAAQABAAAAgBQACgBADAAIAVAAIAFgBQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAgBQAAgKgGgGQgHgHgJAAQgMAAgGAKQgGALAAAPQAAAPAJALQAIAMAMAAQAHAAAFgCQAGgCAEgDIAEgDQAFgEADAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAACgCAEIgHAHQgJAIgIADQgIADgKAAQgVAAgOgPg");
	this.shape_10.setTransform(12.6,-5.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006F46").s().p("AAWAzQgKgggHgHQgGgGgLgBQgIABAAgHQAAgFAHAAQAQAAAIgHQAIgHAAgNQAAgOgIgHQgIgHgPABIgLABQgDABgBACIgBAJIAAAUIAAAtIAAAfQABAGACACIAEACQAHADAAAEQAAAEgGABQgGACgQABQgQgBgFgCQgGgBAAgEQAAgEAGgDIAFgCQACgCABgMIABgsIgBgmQgBgPgBgCQgBgBgGgCQgFgCAAgEQAAgEADgCQADgCAHAAIAWAAIAUAAIAQgBQAWAAAMAKQALAKAAARQAAAOgHAKQgIAKgOADIAAACQALACAGAGQAGAGAFARIADAKQAEAQAGAAIACAAIAEAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAAEgGADQgFAEgKAAQgUgBgHgXg");
	this.shape_11.setTransform(0,-7.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006F46").s().p("AgUALIgEgBIgBgFIABgEIACgFIADgEIAFgBIAGAAIAIABIARgBIADAAIAEABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAAGgEAEQgDAFgEAAIgFAAIgGAAIgVABIgDAAg");
	this.shape_12.setTransform(-11.1,-5.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006F46").s().p("AguBDQgFgEAAgGQAAgGAEgDQADgEAGAAIAEABIADACIADAEQACAEACAAQAFAAAGgHQAFgIAAgIQAAgJgHgQIgBgCIgRgjIgJgUQgBgDgHgDIAAAAQgDgBgBgCQAAAAgBgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQgBgFAGgCQAFgBAPAAQAPAAAFABQAFACAAAEIgBADIgCACIgDACQgBAAgBABQAAAAgBAAQAAABgBAAQAAAAAAABIACAIIAIAUIAHATQADAFACAAQAAAAADgFIAHgQIAHgUIADgKQgBgDgFgDQgGgDAAgDQAAgDAFgCQAFgBALAAQAMAAAFABQADACAAAEQABAEgGABIgFACQgFADgGARIgEAIIgNAgQgQAqgKANQgLAMgPAAQgHAAgFgEg");
	this.shape_13.setTransform(-19.8,-3.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006F46").s().p("AgFA9QgFgCgDgDQgDgDgCgFQgCgHABgPIAAg1IgKAAIgDgBIgBgCIAAgDQAAgDALgKIAEgDIAEgEQALgJADAAIACABIABADIAAATIAXAAIAEABIABADIAAADIgBADQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAIgUAAIgCAAIgBADIAAAxQABANACAEQABAEAHgBQADAAAFgCIAHgBQABAAAAAAQAAAAABAAQAAABABAAQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAFgIAGQgJAFgLAAQgGAAgFgCg");
	this.shape_14.setTransform(-28.7,-6.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006F46").s().p("AgeAzQgFgCAAgFQAAgEAFgBIADgBQACgBABgEQACgDAAgIIgBgHIAAgIIAAgGIAAgXQgBgHgCAAIgFgCQgGgCAAgEQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBABAAIAGgEIAOgEIAJgBQAFAAABANIAAACIABAAQAFgHAFgFQAGgEAGAAQAHAAAEAEQAEAFAAAGQAAAIgDADQgDAFgGAAIgFgBIgEgEIgDgEQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAAAQgHAAgDAKQgCAKAAAdIABAOQABAFADAAIAEACQAGABAAAFQAAAEgGACQgFABgNAAQgQAAgFgBg");
	this.shape_15.setTransform(-36.2,-5.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006F46").s().p("AASAwIgFgGIgFACQgMAJgMAAQgPAAgJgJQgJgIAAgOQAAgQALgJQAMgJAVAAQAFAAACACQADABAAAEQAAAFgGAAQgKAAgGAFQgHAFAAAIQAAAJAGAFQAFAEAJAAQAJABAEgFQAEgEAAgLIAAgmQAAgJgDgFQgEgEgHAAQgFgBgEADQgEACgEAFIgCACQgGAIgHAAQgEAAgDgCQgCgDAAgFQAAgJAMgHQALgGATAAQAKAAAIADQAJADAEAGQADADABAHQACAGAAAOIAAAgIABAJQAAABAAAAQABABAAAAQAAAAABABQAAAAABAAIADABQAGACAAADQAAAFgHAEQgGAEgKAAQgEAAgFgFg");
	this.shape_16.setTransform(-45.8,-5.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006F46").s().p("Ag0BIQgGgCAAgEQAAgEAHgDIAEgCQACgBABgMIABgsIgBgmQAAgPgCgCQgBgCgFgCQgGgCAAgDQAAgEAEgCQADgCAGAAIALAAIALAAIAVAAIAPgBQAXAAALAKQAMAKAAATQAAAWgOALQgOAKgbAAQgKAAAAgHQAAgHAIAAQANAAAIgGQAIgHAAgPQAAgOgIgGQgIgHgQAAIgKABQgDABgBADIgBAJIgBAVIAAAsIABAdQAAAIACABIAFACQAGADAAAEQAAAEgGACQgFACgQAAQgQAAgGgCg");
	this.shape_17.setTransform(-57.4,-7.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.partyreadyrecipesmobileleaderboard, new cjs.Rectangle(-65.9,-21.9,199.9,28.2), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.kalemobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAfQgNgNAAgSQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAASgNANQgNANgSAAQgRAAgNgNgAgYgYQgKAKAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgPAAQgOAAgKAKgAAMAZIgOgVIgFAAIAAAVIgJAAIAAgzIATAAQARAAAAAPQAAANgNABIAPAWgAgHgDIAGAAQANAAAAgIQAAgHgMAAIgHAAg");
	this.shape.setTransform(17.1,7.8,0.131,0.131);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjnEaQgUgDgIgEQgJgFAAgNQAAgKAGgHQAFgHAJAAIARAAQAKAAAFgLQADgKgBgXIAAl5QABgXgDgKQgFgLgKAAIgRAAQgJAAgFgHQgGgHAAgKQAAgNAJgFQAIgEAUgDQBegNBrAAQBNAAA1ASQA1ASAnAoQAlAlAVA5QATA4AABEQAABNgZA9QgZA+gwAlQglAegvAOQgxAOhEAAQhrAAhegNgAgvjrQgcAFgKALQgKAMAAAhIAAFjQAAAhAVALQANAHAnADQBNAEAshAQAqg/ABhwQAAhwgrg/Qgrg/hKAAIgdADg");
	this.shape_1.setTransform(8.2,4,0.131,0.131);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBlQgFgDAAgHIAAiTQAAgKgMAAIgyAAQgKAAAAgPIABgNQACgIAHAAICfAAQAMAAAAASQAAASgLAAIgyAAQgMAAAAAKIABCTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape_2.setTransform(10.7,11.6,0.131,0.131);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAFQACADAAAJQAAAKgCADQgDAGgHAAIh5AAQgIAAAAAJIAAAbQAAAKAKAAIBFAAQALAAAAASQAAAQgKAAIhFAAQgLAAAAALIAAAeQAAAKAKAAIB4AAQAKAAAAATQAAARgKAAg");
	this.shape_3.setTransform(6.9,11.6,0.131,0.131);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAxBgIhAhGQgLgJgTAAQgFAAgEAEQgDAFAAAGIAAA8QAAAMgVAAQgRAAAAgNIAAi0QAAgIAFgCQAEgCALAAQASAAAAAMIAAA3QAAANAJAAQALAAAFgDQAEgBAFgFIBJhDQANgLAMAMQAMALgKAKIhAA6QgJAIAJAJIBOBWQAIAIgGAFQgFAFgNAAQgTAAgHgIg");
	this.shape_4.setTransform(3,11.6,0.131,0.131);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAvBeIghgxQgFgJgKAAIgtAAQgEAAgDADQgDACgBAFIABAwQAAAHgKACIgPAAQgNAAAAgLIAAi6QAAgIAJAAIBrAAQAgAAAUASQAVAUgBAgQAAAXgOAPQgIAJgPAJQgHAIAEAFIAiAyQAFAHgFAFQgEAEgPAAQgRAAgFgJgAg5g4IAAAuQABAFAEADQAEACAFAAIA+AAQAQAAALgHQALgKAAgPQAAgRgLgJQgLgJgQAAIg+AAQgOAAAAALg");
	this.shape_5.setTransform(-1.5,11.6,0.131,0.131);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCBgIgOgbQgCgHgHAAIhTAAQgJAAgEALIgMAXQgDAHgSAAQgWAAAFgMIBZi4QAFgKAKAAQALAAAFAJIBXC6QADAGgJAEQgGACgIAAQgPAAgDgIgAgEgdIgYAyQgDAIAIAAIAwAAQABAAABAAQAAgBABAAQABAAAAAAQAAgBABAAQACgCgCgDIgZgzQgBgDgEAAQgCAAgCADg");
	this.shape_6.setTransform(-5.8,11.6,0.131,0.131);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABZBlQgFgDAAgFIgOhrQgCgHgFAAQgDAAgDAEIgxA+QgEAFgFAAQgHAAgEgHIgtg7QgCgDgEAAQgFAAgBAHIgOBpQgCAKgTAAQgGAAgFgCQgGgDAAgGIAVixQACgJADgCQAEgFALAAQAKAAAFAIIA4BPQAFAIAEAAQAEAAAHgIIA7hQQAEgIALAAQAGAAADACQAEADACAJIAVC1QABAKgXAAQgFAAgFgCg");
	this.shape_7.setTransform(-10.3,11.6,0.131,0.131);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AipF/QhPhTAAiLQAAhZAghEQAghCA6gnQAZgTAmgTQAmgTAngOQAKgDgDgJQgCgKgNADQg7ALgrgSQgWgJgdgRQghgUgJgEQgvgWg6AZQgVAJgMgLQgLgLAGgXQAXhWBDg3QBKg9BQAXQA0APAlA0QAmA2AfALQATAGgBAPQAAAOgRADQgaAFgjgRQgggPgdgbQgfgcgvgCQgsgCgbAVQgLAIADAHQAEAHAKgDQAggHAdAGQAoAIAbAgQAkAoAuAPQA4ASAugfIAZgWQANgNAMAEQAPAEgBAUQgBAUgTAZQgiAsg+AeQhFAjgeAdQgwAwgTA9QgPAzAABQQAAByAqBAQAqBABKAAQBKAAArhCQAqhBAAhwQAAhfgXg4QgZg6g2gVQgbgKAFgTQAFgUAhgEQA3gGA8AsQBoBOAACjQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape_8.setTransform(1.9,-7.1,0.131,0.131);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABnDxQhFg2gYheIgBgDQgCgLgHABQgGgBgCALIgBABQgYBghGA2QhIA2hoAAQh+AAhMhQQhMhRAAiFQAAiGBMhRQBLhQCAAAQBpAABHA2QBHA3AXBgQACALAGgBQAHAAACgLIABAAQAXhgBGg2QBHg2BoAAQB/AABNBPQBMBQAACGQAACHhMBRQhNBQiBAAQhmAAhHg2gACniqQgpA/AABtQAABtApA9QAoA+BIAAQBGAAApg/QAphAAAhrQAAhqgqhAQgpg/hHAAQhGAAgoA/gAmFiqQgoA/AABtQAABtAoA9QAoA+BIAAQBGAAApg/QAphAAAhrQAAhqgqhAQgpg/hHAAQhGAAgoA/g");
	this.shape_9.setTransform(-2.8,4,0.131,0.131);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ai5EbQgWAAgJgFQgIgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAEgLQADgJAAgYIAAl7QAAgXgDgKQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFvAAQAaAAAEAVIAMA7QAEAQgFAJQgFAJgMAAQgPAAgHgOQgEgFgFgNQgFgQgPgFQgNgEggAAIhtAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAFADAdAAIBFAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgXIAAgFQgCgNgIgDQgHgEgbAAIhFAAQgeAAgEAEQgIAFAAAZIAACLQAAAbACAGQAGALAMAAIATAAQAKAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape_10.setTransform(-12.9,4,0.131,0.131);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhTEbIgTgEQgIAAgKAJQgKAIgJAAQgLAAgGgHQgGgGgEgQIgVhUQgCgIAAgJQAAgMAHgIQAIgHAMAAQAMAAAJALIAMARQAWAfAhASQAiASAkAAQApAAAagVQAZgUAAgiQAAghgbgfQgbgdg/gsIhNg2QgSgPgTgWQgggmAAgzQAAg9ArgmQArgmBGAAQAlAAAjAIIAWAFIALACQAJAAALgIQAKgHAIAAQASAAAGAYIAUBcQABAEAAAIQAAAIgHAGQgHAGgKAAQgMAAgLgOQgNgVgHgIQgGgGgOgLQgjgbgtAAQgcAAgSAPQgRAQAAAaQAAAXAJALQAMASAbAWIApAdQAzAkAWARQAXASAUAUQAWAWAMAfQAMAeAAAhQAABJgyAtQgzAthUAAQgzAAglgNg");
	this.shape_11.setTransform(14.5,4,0.131,0.131);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah+EYQgLgJgHgYIhJjYQgBgFgEAAQgFAAgBAFIhNDYQgKAagHAIQgNAIgQABQgTgBgKgIQgLgKgJgYIimm+QgKgZgHgIQgHgHgUgFQgOgBgFgGQgFgFAAgKQAAgXAdAAICvAAQAcAAAAAXQAAAMgHAEQgHAFgRABQgOACgGAEQgGAFAAALQAAAIADALIBzFGQACAFAFAAQAEgBACgFIA/i1QAIgZgHgYIglhuQgEgJgHgFQgGgEgPgEQgNgEgGgEQgFgGAAgJQAAgaAdAAICnAAQAdAAAAAXQAAATgcAFQgRABgFAFQgGAFAAALQAAALAIAZIBfEsQACAFAEAAQAFgBABgFIBdk6QAEgLAAgJQAAgTgdgDQgbgCAAgWQAAgMAHgGQAIgGARAAIElAAQAVAAAIAGQAIAFAAAOQAAAKgGAHQgGAHgJAAIgQAAQgLAAgFAKQgCAJAAAZIAABuQAAAdAFAHQAGAGAXAAIB0AAQAXAAAHgHQADgEAAgGIABgfIAAhoQAAgbgDgHQgFgKgKAAIgQAAQgKAAgHgHQgGgHAAgKQAAgOAIgFQAJgGAWAAICaAAQAWAAAJAGQAJAFAAAOQAAAKgHAHQgGAHgJAAIgSAAQgEAAgEADQgFAEgBADQgDAKAAAYIAAF8QAAAYADALQABADAFAEQAEACAEAAIASAAQAJAAAGAIQAHAGAAAKQAAAOgJAGQgIAEgXAAIiaAAQgWAAgIgEQgIgGAAgOQAAgKAGgGQAHgIAJAAIAQAAQAKABAFgKQADgIAAgbIAAh8IgBgdQAAgHgDgDQgHgIgXAAIh0AAQgXAAgGAHQgFAGAAAeIAACAQAAAZACAKQAFAKALgBIAQAAQAJAAAGAIQAGAGAAALQAAANgIAGQgIAEgVAAIiaAAQgWAAgJgEQgIgGAAgOQAAgKAGgGQAHgIAJAAIARAAQAEAAAFgCQAEgEABgDQADgIAAgbIAAl8QAAgwgkAEQgLABgHAJQgIAKgGAVIiHGzQgJAfgKAMQgLAKgTABQgTAAgLgKg");
	this.shape_12.setTransform(-9.8,-4.8,0.131,0.131);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AihEbQgWAAgIgFQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDACgEQADgIAAgXIAAmAQAAgZgDgHQgDgMgLAAIgRAAQgKABgGgHQgHgHAAgKQAAgOAJgFQAJgGAWAAICcAAQAWAAAJAGQAJAFAAAOQAAAKgGAHQgHAHgJgBIgSAAQgOAAgDAMQgDAFAAAbIAAFkQAAAdACAJQACAJAIAFQAGAFALABQALACAaAAIAwAAQAvAAAPggIAIgQQAIgPAPAAQAMgBAFAJQAFAJgEAQIgNBCQgEAVgaAAg");
	this.shape_13.setTransform(9.1,-4.9,0.131,0.131);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjREWQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDABgEQAEgIAAgaIAAl7QAAgZgEgIQgBgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgKQAAgNAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QADAQgFAJQgFAIgMAAQgPAAgGgNQgDgCgGgQQgGgQgPgFQgMgEggAAIhQAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAEADAeAAIAmAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAIgOAAQgTAAgEgWIAAgFQgCgNgIgDQgHgEgbAAIgmAAQgeAAgEAEQgIAFAAAZIAABsQAAAiADALQADALAKAEQAPAFAiAAIBVAAQAvAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgDAQIgNBCQgFAVgaAAIlhAAQgWAAgIgFg");
	this.shape_14.setTransform(15,-4.9,0.131,0.131);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0C6E47").s().p("AqoZMQk7iEjyjzQjxjxiFk6QiKlGAAljQAAljCKlGQCFk6DxjzQDzjxE6iFQFFiKFjAAQFkAAFFCKQE7CFDxDxQDyDzCFE6QCKFGAAFjQAAFjiKFGQiFE6jyDxQjxDzk7CEQlFCKlkAAQljAAlFiKg");
	this.shape_15.setTransform(0,0,0.131,0.131);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.kalemobileleaderboard, new cjs.Rectangle(-23,-23,46,46), null);


(lib.holidayinspirationmobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AAOAzQgGgCAAgEQAAgEAGgCIADgCQADgBABgEIABgQQgBgfgEgIQgDgIgMAAQgEAAgFACQgEAEgEAFQgCAFgBAHIgBAcIABANQABAEACAAIAFACQAEACAAAEQAAAEgEACQgFABgNAAQgRAAgEgBQgFgCAAgFQgBgEAGgBIADgBQACgBABgEIABgLIAAgHIAAgIIAAgKQAAgQgBgEQAAgGgDAAIgFgCQgFgCAAgEQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBABAAIAGgEIAOgEIAKgCQABAAABAAQABAAAAAAQABABAAAAQABAAAAABIABAEIAAAHIAAABIABAAIAAAAIABAAIACgCIADgCQALgKALAAQAHAAAHADQAHADAFAGQAEAFACAIQACAHAAARIAAANIAAAGIAAAGIABAKQABADADACIACABQAFABABAEQAAAEgFACQgFACgPAAQgPAAgEgBg");
	this.shape.setTransform(116.7,-5.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AgkAmQgPgPAAgXQAAgWAQgPQAPgPAWAAQAWAAAOAOQAOAOAAAWQAAAXgPAQQgQAQgVAAQgWAAgOgPgAgTgeQgGAJAAANQAAATAJAOQAIAOAMAAQAKAAAGgJQAGgIAAgOQAAgTgJgNQgIgOgLAAQgKAAgHAIg");
	this.shape_1.setTransform(104.8,-5.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AgRBJQgFgCgBgFQAAgDAGgCIADgBQACgBABgEIABgLIAAgHIAAgIIAAgLQAAgQgBgDQAAgFgDgBIgFgCQgFgCAAgEQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBIAHgDIAPgFIAKgCQAAAAABAAQABAAAAABQABAAAAAAQAAAAAAABQACACAAAFIAAAGIgBAEIAAAZIAAABIgBAZIABAOQABAEACABIAFABQAEACAAAEQAAAEgEACQgFABgNAAQgQAAgEgBgAgMgyQgEgEAAgFQAAgGAEgEQAGgEAGAAQAGAAAFADQADAEAAAGQABAFgFAEQgFAEgGAAQgHAAgEgDg");
	this.shape_2.setTransform(96,-7.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AgEA9QgGgCgDgDQgDgDgCgFQgBgHgBgPIAAg1IgJAAIgDgBIgBgCIAAgDQAAgDALgKIAEgDIAEgEQALgJADAAIADABIABADIAAATIAWAAIAEABIABADIAAADIgBADQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAIgUAAIgCAAIAAADIAAAxQAAANACAEQABAEAHgBQADAAAFgCIAHgBQAAAAABAAQAAAAABAAQAAABABAAQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAFgJAGQgIAFgLAAQgGAAgEgCg");
	this.shape_3.setTransform(89.4,-6.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AASAwIgFgGIgFACQgMAJgMAAQgPAAgJgJQgJgIAAgOQAAgQALgJQAMgJAVAAQAFAAACACQADABAAAEQAAAFgGAAQgKAAgGAFQgHAFAAAIQAAAJAGAFQAFAEAJAAQAJABAEgFQAEgEAAgLIAAgmQAAgJgDgFQgEgEgHAAQgFgBgEADQgEACgEAFIgCACQgGAIgHAAQgEAAgDgCQgCgDAAgFQAAgJAMgHQALgGATAAQAKAAAIADQAJADAEAGQADADABAHQACAGAAAOIAAAgIABAJQAAABAAAAQABABAAAAQAAAAABABQAAAAABAAIADABQAGACAAADQAAAFgHAEQgGAEgKAAQgEAAgFgFg");
	this.shape_4.setTransform(80.2,-5.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AgeAzQgFgCAAgFQAAgEAFgBIADgBQACgBABgEQACgDAAgIIgBgHIAAgIIAAgGIAAgXQgBgHgCAAIgFgCQgGgCAAgEQAAAAAAgBQAAgBAAAAQABgBAAAAQAAgBABAAIAGgEIAOgEIAJgBQAFAAABANIAAACIABAAQAFgHAFgFQAGgEAGAAQAHAAAEAEQAEAFAAAGQAAAIgDADQgDAFgGAAIgFgBIgEgEIgDgEQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAAAgBAAQgHAAgDAKQgCAKAAAdIABAOQABAFADAAIAEACQAGABAAAFQAAAEgGACQgFABgNAAQgQAAgFgBg");
	this.shape_5.setTransform(70.8,-5.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AgRBJQgGgCABgFQAAgDAEgCIADgBQADgBABgEIABgLIAAgHIAAgIIAAgLQAAgQgBgDQgBgFgBgBIgGgCQgFgCgBgEQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAABgBIAFgDIAQgFIAJgCQABAAABAAQAAAAABABQAAAAABAAQAAAAABABQABACAAAFIAAAGIAAAEIgBAZIAAABIAAAZIABAOQABAEABABIAEABQAGACAAAEQAAAEgGACQgFABgNAAQgPAAgEgBgAgMgyQgEgEAAgFQAAgGAFgEQAFgEAGAAQAGAAAEADQAFAEAAAGQgBAFgEAEQgFAEgGAAQgGAAgFgDg");
	this.shape_6.setTransform(63.6,-7.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AgxBFQgFgCAAgEQAAgDAFgCIAFgCQACgDABgIIAAghIAAgPQAAgdgBgHQAAgJgDAAIgFgCQgGgCAAgEQAAAAAAgBQAAgBABAAQAAgBAAAAQABgBAAAAIAGgDIAPgFIAKgBQAAAAABAAQABAAAAAAQABAAAAAAQABABAAAAQABACAAADIAAAFIAAACIABAAIAEgCIAEgDQAGgFAFgCQAGgCAGAAQASAAANANQAMAOAAAWQAAAYgOAPQgOARgUgBQgJABgCgDQgEgCAAgFQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABAAIACABIAEAAQALAAAHgJQAHgKAAgPQAAgRgIgLQgHgLgMABQgJAAgHAFQgGAGAAAQIAABAIABAKQAAADACACQABACAFABIAEABIACACIABADQAAADgGACQgGACgPAAQgPAAgFgCg");
	this.shape_7.setTransform(54.3,-3.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AgHA1IgKgCIgEACIgDABIgCgBIgCgBQgDgEgDgIQgDgIAAgHQAAgEACgCQAAAAABgBQAAAAABAAQAAgBABAAQAAAAABAAQAFAAAEAJIAEAFQADAEAGADQAFACAFAAQAHAAAEgDQAEgEAAgFQAAgJgRgIIgFgDQgQgIgGgGQgFgGAAgKQAAgNAJgIQAJgJAPAAIAGAAIAHACIAFgCIADAAQAFgBAFAJQAFAHAAAKQAAADgCACQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAQgDAAgCgCIgFgHQgEgGgEgCQgEgDgGAAQgFAAgEADQgDADAAAGQAAAEADAEQAEAEAMAGIABABQAcAMAAARQAAAPgKAJQgLAKgRAAg");
	this.shape_8.setTransform(43.9,-5.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("AAOAzQgGgCABgEQgBgEAGgCIADgCQADgBABgEIAAgQQAAgfgEgIQgDgIgMAAQgEAAgFACQgEAEgEAFQgCAFgBAHIAAAcIAAANQABAEACAAIAFACQAEACAAAEQAAAEgEACQgGABgMAAQgQAAgFgBQgFgCAAgFQAAgEAEgBIAEgBQACgBABgEIABgLIAAgHIAAgIIAAgKQAAgQgBgEQAAgGgCAAIgGgCQgFgCAAgEQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBABAAIAGgEIAOgEIAKgCQABAAABAAQABAAAAAAQABABAAAAQABAAAAABIABAEIAAAHIAAABIABAAIAAAAIABAAIACgCIADgCQAKgKAMAAQAHAAAIADQAGADAFAGQAFAFACAIQABAHAAARIAAANIAAAGIAAAGIABAKQABADADACIADABQAEABAAAEQABAEgFACQgFACgPAAQgPAAgEgBg");
	this.shape_9.setTransform(33.4,-5.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006F46").s().p("AgVBHQgFgBgBgEQAAgEAHgDIAFgCQACgCAAgMIABgsIgBgmQAAgPgBgCQgBgBgGgCQgGgCAAgFQABgDAFgCQAEgCARAAQASABAFABQAFACAAADQAAAFgHADIgFABQgBACgBAKIgBAhIAAAwQABASABACQABABAGACQAGACAAAFQgBAEgFABQgGACgQABQgPgBgGgCg");
	this.shape_10.setTransform(23.9,-7.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006F46").s().p("AguBDQgFgEAAgGQAAgGAEgDQADgEAGAAIAEABIADACIADAEQACAEACAAQAGAAAFgHQAFgIAAgIQAAgJgHgQIgBgCIgRgjIgJgUQgCgDgFgDIAAAAQgEgBgBgCQAAAAgBgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgFAFgCQAFgBAPAAQAPAAAFABQAFACAAAEIgBADIgCACIgDACQgBAAgBABQgBAAAAAAQAAABgBAAQAAAAAAABIACAIIAIAUIAHATQADAFACAAQABAAACgFIAHgQIAHgUIACgKQAAgDgFgDQgGgDAAgDQAAgDAFgCQAEgBAMAAQAMAAAEABQAEACAAAEQABAEgGABIgFACQgFADgGARIgDAIIgOAgQgQAqgKANQgLAMgPAAQgHAAgFgEg");
	this.shape_11.setTransform(9.6,-3.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006F46").s().p("AASAwIgFgGIgFACQgMAJgMAAQgPAAgJgJQgJgIAAgOQAAgQALgJQAMgJAVAAQAFAAACACQADABAAAEQAAAFgGAAQgKAAgGAFQgHAFAAAIQAAAJAGAFQAFAEAJAAQAJABAEgFQAEgEAAgLIAAgmQAAgJgDgFQgEgEgHAAQgFgBgEADQgEACgEAFIgCACQgGAIgHAAQgEAAgDgCQgCgDAAgFQAAgJAMgHQALgGATAAQAKAAAIADQAJADAEAGQADADABAHQACAGAAAOIAAAgIABAJQAAABAAAAQABABAAAAQAAAAABABQAAAAABAAIADABQAGACAAADQAAAFgHAEQgGAEgKAAQgEAAgFgFg");
	this.shape_12.setTransform(-1,-5.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006F46").s().p("AAUBJQgBgBAAgEIAAgEIAAgCIgBgBIgDACIgFADQgGAFgEACQgGACgHAAQgTAAgMgNQgMgOAAgWQAAgZAOgPQAOgPAWAAIAGABQADABACACQABAAAAABQAAABAAAAQABABAAAAQAAABAAAAQAAAGgHAAIgCAAIgDgBQgLAAgHAKQgHAIAAAQQAAASAIAKQAHALAMAAQAJAAAGgGQAGgGAAgLIAAgcIAAguQAAgIgBgCQgBgDgEgBIgDgBQgGgCAAgEQAAgCACgCIAKgFIAMgDIAJgBQAEAAABACQACACAAAEIAAAFIgCA+IABArQABAJABACIAHACQAGACAAADQAAAFgPAFIgKACIgIABQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBg");
	this.shape_13.setTransform(-12.5,-7.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006F46").s().p("AgRBJQgFgCgBgFQAAgDAGgCIADgBQACgBABgEIABgLIAAgHIAAgIIAAgLQAAgQgBgDQAAgFgDgBIgFgCQgFgCAAgEQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBIAHgDIAPgFIAKgCQAAAAABAAQABAAAAABQABAAAAAAQAAAAAAABQACACAAAFIAAAGIgBAEIAAAZIAAABIgBAZIABAOQABAEACABIAFABQAEACAAAEQAAAEgEACQgFABgNAAQgQAAgEgBgAgMgyQgEgEAAgFQAAgGAEgEQAGgEAGAAQAGAAAFADQADAEAAAGQABAFgFAEQgFAEgGAAQgHAAgEgDg");
	this.shape_14.setTransform(-21.9,-7.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006F46").s().p("AgRBJQgEgCAAgEQAAgDAEgCIAFgDQACgCAAgGIABgUIAAgQIAAgSIAAgIQAAgZgBgIQgBgHgCgBIgGgDQgHgBAAgEQAAgBABAAQAAgBAAgBQAAAAABAAQAAgBABAAIAJgEIANgEIAKgCQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQABACAAAFIAAAIIgBBIIABAjQABAHABACIAGADQAEACAAAEQAAAEgEABQgGACgNAAQgOAAgGgCg");
	this.shape_15.setTransform(-28,-7.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006F46").s().p("AgkAmQgPgPAAgXQAAgWAQgPQAPgPAWAAQAWAAAOAOQAOAOAAAWQAAAXgPAQQgQAQgVAAQgWAAgOgPgAgTgeQgGAJAAANQAAATAJAOQAIAOAMAAQAKAAAGgJQAGgIAAgOQAAgTgJgNQgIgOgLAAQgKAAgHAIg");
	this.shape_16.setTransform(-36.6,-5.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006F46").s().p("AAXBHQgGgBAAgEQAAgEAGgDIAFgCQACgBAAgHIABgYIAAgOIgBgEQgBgCgFgBIgYAAIgVAAQgFAAgCACIgBADIgBAHIAAAJIABAYQABAHABABIAFACQAGADAAAEQAAAEgGABQgFACgQABQgQgBgGgCQgGgBAAgEQAAgEAHgDIAEgCQACgCABgNIABgrIgBglQAAgQgCgCQgBgBgFgCQgGgCAAgFQAAgDAFgCQAFgCASAAQASAAAEACQAFACAAADQAAAFgGADIgFABQgCACAAAGIgBAeQAAAEAEACQAEABAOAAIAIAAIAVAAQAHgBACgBIABgDIAAgEIAAgEIgBgZQAAgFgCgCIgFgBQgGgDAAgFQAAgDAFgCQAFgCARAAQATABAEABQAFACAAADQAAAFgHADIgEABQgCACgBAOIgBAoIABAoQABAOABADQABABAFACQAGACAAAFQAAAEgGABQgGACgQABQgQgBgFgCg");
	this.shape_17.setTransform(-50.2,-7.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidayinspirationmobileleaderboard, new cjs.Rectangle(-60,-21.9,185.1,28.2), null);


(lib.fillinboxmobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AAOBJQgFgBAAgEQAAgFAFgBIAEgCQACgBACgFIAAgPQAAgggEgIQgEgIgLAAQgEAAgFADQgFADgDAFQgCAFgBAHIgBAcIABANQABAEACABIAEACQAFABAAAFQAAAEgFABQgFABgNAAQgQAAgFgBQgFgCAAgEQAAgEAFgBIADgBQADgCABgFQABgDAAgMIAAgQIAAgQIgBgtQgBgMgBgCQgBgBgGgCQgGgCAAgDQAAgCACgCIAMgGIAKgDIAKAAQADgBABACIABAHIAAAEIgBApIAAAEIABADIACABIACgDIADgEQAGgEAFgDQAFgDAHABQARgBAJALQAIAMAAAWIAAAJIAAATIAAAGIABAGQABADACACIADABQAFABAAAEQAAAEgFACQgEABgRAAQgNAAgFgBg");
	this.shape.setTransform(110.7,9.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AgEA9QgGgCgDgDQgDgDgCgGQgBgGgBgPIAAg1IgJAAIgDgBIgBgCIAAgDQAAgDALgKIAEgDIAEgEQALgJADAAIADABIABADIAAATIAWAAIAEABIABADIAAADIgBAEQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAIgUAAIgCAAIAAADIAAAyQAAANACADQABAEAHgBQADAAAFgCIAHgBQAAAAABAAQAAAAABAAQAAABABAAQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAFgJAGQgIAFgLAAQgGAAgEgCg");
	this.shape_1.setTransform(101.1,10.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AgRBJQgGgCABgFQAAgDAEgCIAEgBQACgBABgEIABgLIAAgHIAAgIIAAgLQAAgQgBgDQgBgFgBgBIgGgCQgFgCgBgEQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAABgBIAFgDIAQgFIAJgCQABAAABAAQAAAAABABQABAAAAAAQAAAAABABQABACAAAFIAAAGIAAAEIgBAZIAAABIAAAZIABAOQABAEABABIAFABQAEACAAAEQAAAEgEACQgGABgMAAQgQAAgEgBgAgMgyQgEgEAAgFQAAgGAFgEQAFgEAGAAQAGAAAEADQAFAEAAAGQgBAFgEAEQgFAEgGAAQgGAAgFgDg");
	this.shape_2.setTransform(94.3,9.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AAGALIgLgfQgHgPgEgCIgDgBQgGgDAAgDQAAgEAFgCQAFgBAPgBQAOABAFABQAGACAAAEIgBADIgCABIgEACQgEACAAACIACAHIAJAVIAIATQADAEABABIADgDIAEgJIALgZQAEgKAAgEIAAgDIgDgCIgDgCQgFgBABgDQgBgEAFgCQAFgBAMgBQALABAFABQADACAAAEQAAADgEACIgEACQgFACgJAVIgDAFIgEAJQgXA1gGAAQgHAAgSgqgAg7AGIgDgGIgGgRQgHgSgFgCIgDgBQgFgDgBgDQABgEAFgCQAFgBAQgBQAOABAFABQAFACAAAEIgBADIgBABIgEACQgEACAAACIACAJIAIATIAJASQACAGABAAQADgBADgGIADgHIADgDIAEgBIADABQAAAAABABQAAAAAAABQAAAAAAABQABAAAAABQAAADgDAFIgPAgQgFAHgEABQgHgBgUgug");
	this.shape_3.setTransform(83.1,11.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AAJAxQgFgCAAgEQAAgDADgBIADgDQABgCgFgHIgRgbIgRgYQgFgIgEgDQgBgBgGgBQgEgCAAgDQAAgEAFgCQAFgCANAAQAPAAAFACQAFABAAAEQAAADgDACIgDAEQAAACALARIABABIADgGIAJgOIgDgEQgEgCAAgDQAAgDAFgCQAFgCALAAQAIAAAFACQAEACAAADQAAAEgHADIgFACQgFACgGAIQgGAHgHANIASAbIAJALIAHAEQAFABAAAEQABAEgGACQgFACgNAAQgOAAgGgCgAgvAxQgFgCAAgDQAAgFAIgCIAFgCQADgBAGgHIAIgMIADgDIADgBQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAIABAEQAAADgCADQgIALAAACQAAABAEACQAEACAAADQAAAEgFACQgGACgLAAQgIAAgEgCg");
	this.shape_4.setTransform(63.6,11.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AgkAmQgPgPAAgXQAAgWAQgPQAPgPAWAAQAWAAAOAOQAOAPAAAVQAAAXgPAQQgQAQgVAAQgWAAgOgPgAgTgdQgGAHAAAOQAAATAJAOQAIAOAMAAQAKAAAGgJQAGgIAAgOQAAgTgJgOQgIgNgLAAQgKAAgHAJg");
	this.shape_5.setTransform(52.7,11.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AgNBJQgJgCgFgFIgHAFIgGABIgDAAIgEgCIAAgBQAEgEABgJQACgJAAgXIAAgXIAAgWIgBgZQgBgHgCgBIgFgCQgHgBAAgEQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAgBIAKgEIAMgEIAKgBQAEAAABABQACACAAADIgBAGIgBAeIABAsIAAAaQAAAPAEAFQAFAFALAAQAMAAAHgKQAIgLAAgTQAAgQgHgJQgHgKgMAAIgDABIgCAAQgIAAAAgHQAAgFAIgDQAGgDAJAAQATAAALANQAMANAAAWQAAAagOAPQgPAPgYAAQgJAAgIgCg");
	this.shape_6.setTransform(40.3,9.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AANAzQgEgCAAgEQAAgEAEgCIAFgCQACgBABgEIAAgQQAAgfgDgJQgFgHgLAAQgEAAgFADQgEADgEAGQgBAEgBAHIgBAcIABANQABAEABAAIAFACQAEACAAAEQAAAEgEACQgFABgNAAQgRAAgEgBQgGgCABgFQAAgEAEgBIAEgBQACgBABgEIABgLIAAgHIAAgIIAAgKQAAgQgBgFQgBgEgBgBIgGgCQgFgDgBgDQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBABAAIAFgEIAPgEIAKgCQABAAABAAQABAAAAAAQABABAAAAQABAAAAABIABAEIAAAIIABABIAAAAIABAAIAAgBIACgCIACgCQALgKAMAAQAIAAAHADQAGADAFAGQAFAFACAIQACAHAAARIAAANIAAAGIAAAGIAAALQACADACABIADABQAEABAAAEQABAEgFACQgFACgQAAQgOAAgFgBg");
	this.shape_7.setTransform(28.7,11.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AgUBHQgHgBAAgEQABgEAGgDIAEgCQADgCABgMIABgsIgBglQgBgPgBgDQgCgBgFgCQgFgCgBgEQAAgEAGgCQAEgCARAAQASABAFABQAFACgBAEQABAEgHADIgFACQgCABAAAKIgBAiIABAvQABASAAABQACACAFADQAGABgBAFQAAAEgFABQgGACgQAAQgPAAgFgCg");
	this.shape_8.setTransform(19.2,9.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("AgeAzQgFgCAAgFQAAgEAFgBIADgBQACgBABgEQACgDAAgIIgBgHIAAgIIAAgGIAAgXQgBgHgCAAIgFgCQgGgDAAgDQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABAAIAGgEIAOgEIAJgCQAFAAABAOIAAACIABAAQAFgHAFgFQAGgEAGAAQAHAAAEAEQAEAFAAAGQAAAIgDADQgDAFgGAAIgFgBIgEgEIgDgDQAAgBAAgBQgBAAAAAAQAAgBAAAAQgBAAAAAAQgHAAgDAKQgCAKAAAdIABAOQABAFADAAIAEACQAGABAAAFQAAAEgGACQgFABgNAAQgQAAgFgBg");
	this.shape_9.setTransform(6.3,11.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006F46").s().p("AAWAzIgBgFIAAgGIAAgBIgBAAQAAAAAAAAQgBAAAAABQgBAAAAAAQgBABAAABIgBABQgGAFgGACQgFADgHgBQgIABgHgDQgGgDgFgFQgFgGgCgJQgCgHAAgWIAAgHIAAgHIAAgCQAAgIAAgCQgCgDgEgBIgDgCQgHgBAAgDQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAAAgBIAKgEIANgEIALgBQABAAABAAQAAAAABABQABAAAAAAQAAAAABABIABAGIAAAFIgBAlQgBAUAFAIQAEAIAKAAQALAAAGgKQAEgLAAgYIAAgHQABgIgCgCQgBgDgDgBIgFgCQgFgBgBgDQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAABgBQACgBAHgDIANgEIALgBQABAAAAAAQABAAABAAQAAABABAAQAAAAABABIAAAGIAAAGIAAApIAAARIAAAHQABAEAFACIACABQAGACgBADQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQgCACgEABIgPAFIgKACQgBAAgBAAQgBAAAAAAQgBgBAAAAQgBAAAAgBg");
	this.shape_10.setTransform(-4.2,11.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006F46").s().p("AgkAmQgPgPAAgXQAAgWAQgPQAPgPAWAAQAWAAAOAOQAOAPAAAVQAAAXgPAQQgQAQgVAAQgWAAgOgPgAgTgdQgGAHAAAOQAAATAJAOQAIAOAMAAQAKAAAGgJQAGgIAAgOQAAgTgJgOQgIgNgLAAQgKAAgHAJg");
	this.shape_11.setTransform(-16,11.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006F46").s().p("AgVBHQgFgBgBgEQAAgEAHgDIAFgCQACgDABgpIAAgJIgMgUIgTgeQgGgJgEgBIgEgDQgHgCAAgEQAAgFAFgBQAFgCATAAQAUAAAEACQAFABABAFQgBAEgHADIgBAAIgDACIgBADQAAADAFAGIATAgIARgaQAGgJAAgDQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAgBgBQgBgBgEgCIgGgEIgBgDQAAgFAEgBQAEgCARAAQARAAAEACQAEABAAAFQAAAEgGADIgIADQgEADgJAPIgZAoIAAASQAAAhADADIAFACQAHADgBAEQAAAEgFABQgGACgQAAQgPAAgGgCg");
	this.shape_12.setTransform(-28.4,9.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006F46").s().p("AgQBJQgGgCAAgEQABgDAEgCIAFgDQABgCABgGIABgUIAAgQIAAgSIAAgIQAAgZgBgIQgBgHgCgBIgGgDQgHgBABgEQAAgBAAAAQAAgBAAgBQAAAAABAAQAAgBABAAIAJgEIANgEIAKgCQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQACACgBAFIAAAIIgBBIIAAAjQACAHABACIAFADQAFACABAEQgBAEgFABQgEACgOAAQgPAAgEgCg");
	this.shape_13.setTransform(-44,9.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006F46").s().p("AgRBJQgEgCAAgEQgBgDAFgCIAFgDQABgCACgGIAAgUIAAgQIAAgSIAAgIQAAgZgBgIQgBgHgCgBIgGgDQgGgBgBgEQAAgBABAAQAAgBAAgBQAAAAABAAQAAgBAAAAIAJgEIAPgEIAJgCQABAAAAAAQABAAABABQAAAAAAAAQABABAAAAQACACAAAFIgBAIIgBBIIABAjQABAHABACIAFADQAGACgBAEQABAEgGABQgEACgOAAQgPAAgFgCg");
	this.shape_14.setTransform(-49.9,9.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006F46").s().p("AgRBJQgFgCgBgFQAAgDAGgCIADgBQACgBABgEIABgLIAAgHIAAgIIAAgLQAAgQgBgDQAAgFgDgBIgFgCQgFgCAAgEQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBIAHgDIAPgFIAKgCQAAAAABAAQABAAAAABQABAAAAAAQAAAAAAABQACACAAAFIAAAGIgBAEIAAAZIAAABIgBAZIABAOQABAEACABIAFABQAEACAAAEQAAAEgEACQgFABgNAAQgQAAgEgBgAgMgyQgEgEAAgFQAAgGAEgEQAGgEAGAAQAGAAAFADQADAEAAAGQABAFgFAEQgFAEgGAAQgHAAgEgDg");
	this.shape_15.setTransform(-55.7,9.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006F46").s().p("AgzBIQgGgBABgEQgBgFAGgBQAFgDABgCQACgBAAgPIABgoIgBglQgBgQgBgCIgGgDQgGgDABgDQAAgEAEgCQAFgBASgBIA9AAIAKgBIAFAAIADAAIACACQACAEABAGQACAHAAAGQAAAEgBACQgCADgDAAQgEAAgDgHIgDgFQgDgDgEgBQgFgCgGAAIgPAAIgOABQgEABgCACQgCACgBAHIgBATIAAAIIABAHQAAAAABAAQAAAAABABQAAAAABAAQAAAAABAAIAQAAQAIAAADgCQADgCABgHIAAgCQACgLAFAAQAEAAADAGQABAGAAATQAAATgBAFQgCAGgFgBQgFAAgCgKIAAgCQgBgGgDgCQgDgDgIAAIgQAAQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAgBABQgBABAAAHIAAAIIABAdQAAAFADACIAEACQAGADABAEQAAAEgHABQgFACgQAAQgRAAgFgCg");
	this.shape_16.setTransform(-64.7,9.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.fillinboxmobileleaderboard, new cjs.Rectangle(-73.2,-4.9,192.4,28.2), null);


(lib.diytipsmobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgHA1IgKgCIgEACIgDABIgCgBIgCgBQgDgEgDgIQgDgIAAgHQAAgEACgCQAAAAABgBQAAAAAAAAQABgBABAAQAAAAABAAQAFAAAEAJIAEAFQADAEAGADQAFACAFAAQAHAAAEgDQAEgEAAgFQAAgJgRgIIgFgDQgQgIgGgGQgFgGAAgKQAAgNAJgIQAJgJAPAAIAGAAIAHACIAFgCIADAAQAFgBAFAJQAFAHAAAKQAAADgCACQgBABAAAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgDAAgCgCIgFgHQgEgGgEgCQgEgDgGAAQgFAAgEADQgDADAAAGQAAAEADAEQAEAEAMAGIABABQAcAMAAARQAAAPgKAJQgLAKgRAAg");
	this.shape.setTransform(60.4,-5.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AgxBFQgFgCAAgEQAAgDAFgCIAFgCQACgDABgIIAAghIAAgPQAAgdgBgHQAAgJgDAAIgFgCQgGgCAAgEQAAAAAAgBQAAgBABAAQAAgBAAAAQABgBAAAAIAGgDIAPgFIAKgBQAAAAABAAQABAAAAAAQABAAAAAAQABABAAAAQABACAAADIAAAFIAAACIABAAIAEgCIAEgDQAGgFAFgCQAGgCAGAAQASAAANANQAMAOAAAWQAAAYgOAPQgOARgUgBQgJABgCgDQgEgCAAgFQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABgBQAAAAABAAQABAAAAAAIACABIAEAAQALAAAHgJQAHgKAAgPQAAgRgIgLQgHgLgMABQgJAAgHAFQgGAGAAAQIAABAIABAKQAAADACACQABACAFABIAEABIACACIABADQAAADgGACQgGACgPAAQgPAAgFgCg");
	this.shape_1.setTransform(49.6,-3.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AgRBJQgFgCgBgFQAAgDAGgCIACgBQADgBABgEIABgLIAAgHIAAgIIAAgLQAAgQgBgDQgBgFgCgBIgEgCQgHgCABgEQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBIAHgDIAPgFIAKgCQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQACACAAAFIAAAGIgBAEIAAAZIAAABIgBAZIABAOQACAEACABIADABQAFACABAEQgBAEgFACQgEABgOAAQgOAAgFgBgAgMgyQgEgEAAgFQAAgGAEgEQAGgEAGAAQAGAAAEADQAEAEAAAGQABAFgFAEQgFAEgGAAQgGAAgFgDg");
	this.shape_2.setTransform(40.8,-7.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AgUBIQgGgCAAgEQAAgEAFgCQAGgCABgCQABgCABgRIAAguIAAgbIgBgQQAAgBAAgBQAAAAgBgBQAAAAAAgBQgBAAAAgBIgGAAIgEAAQgHAAgEACQgEABgDAEIgDAHIgDAHIgDADIgEABQgDAAgBgCQgCgDAAgGQAAgOAEgIQADgIAFAAIABAAIAUABIA7AAIAVgBIABAAQAFAAADAIQADAIAAAOQAAAGgCADQgBACgDAAIgEgBIgDgDIgDgHIgDgHQgDgEgEgBQgEgCgHAAIgEAAIgGAAQAAABAAAAQgBABAAAAQAAABAAAAQgBABAAABIgBAQIAAAbIABAuQAAARABACQABACAGACQAFACAAAEQAAAEgFACQgGACgQAAQgPAAgFgCg");
	this.shape_3.setTransform(31.1,-7.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AgVBHQgFgBgBgEQAAgEAHgDIAFgCQACgDABgpIABgJIgNgTIgTgfQgGgJgEgCIgEgCQgHgCAAgEQAAgEAFgCQAFgCATAAQAUAAAEACQAFACABAEQgBAEgHADIgBAAIgDACIgBADQAAADAFAGIATAgIARgaQAGgKAAgCQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAgBgBQgBgCgEgBIgGgEIgBgDQAAgEAEgCQAEgCARAAQARAAAEACQAEACAAAEQAAAEgGADIgIADQgEADgJAPIgZAoIAAASQAAAiADACIAFACQAHADgBAEQAAAEgFABQgGACgQABQgPgBgGgCg");
	this.shape_4.setTransform(12.1,-7.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AgUBHQgHgBAAgEQABgEAGgDIAEgCQADgCABgMIABgsIgBgmQgBgPgBgCQgCgBgFgCQgFgCgBgFQAAgDAGgCQAEgCARAAQASABAFABQAFACgBADQABAFgHADIgFABQgCACAAAKIgBAhIABAwQABASAAACQACABAFACQAGACgBAFQAAAEgFABQgGACgQABQgPgBgFgCg");
	this.shape_5.setTransform(2.1,-7.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AgVBJIgNAAIgIAAIgJAAQgMAAgEgBQgEgCAAgEQAAgEAFgCQAGgCABgCQABgCABgPIABgnIgBglQgBgQgBgCQgBgCgGgCQgFgCAAgEQAAgEAEgBQAFgCAMAAIAIAAIALAAIANAAIAMAAQAlAAAVATQAUAUAAAjQAAAjgVASQgVASgoAAgAgVg5QgFABgBAEQgCAEAAAMIgBAeIABAmIACAUQABACAGADQAHACAKAAQAWAAAMgOQALgOAAgdQAAgdgNgQQgNgPgZgBQgIABgEABg");
	this.shape_6.setTransform(-9.3,-7.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.diytipsmobileleaderboard, new cjs.Rectangle(-19.1,-21.9,86.3,28.2), null);


(lib.ctarectanglevideo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("AumCqIAAlTIdNAAIAAFTg");
	this.shape.setTransform(0,0,0.964,0.733);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectanglevideo, new cjs.Rectangle(-90.1,-12.4,180.3,25), null);


(lib.ctamobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AoEBjIAAjFIQIAAIAADFg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctamobileleaderboard, new cjs.Rectangle(-51.6,-9.8,103.3,19.8), null);


(lib.blackwideskyscraper = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRBA2FMAAAhsJMAiDAAAMAAABsJg");
	this.shape.setTransform(0,0,0.753,0.867);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackwideskyscraper, new cjs.Rectangle(-82.1,-300,164.3,600.1), null);


(lib.ctarollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(7));

	// Layer 1
	this.instance = new lib.ctarectanglevideo();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.1,-12.4,180.3,25);


// stage content:
(lib.mobileleaderboardslidetransitionfillinboxsomethingdelicious = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//main button, go to specified website on click
		
		this.btn_main.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
			window.open("http://www.wholefoodsmarket.com/stores/list", "_blank");
		}
	}
	this.frame_258 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_282 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(258).call(this.frame_258).wait(24).call(this.frame_282).wait(5));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(160.7,25.5,1.558,0.078,0,0,0,0.2,0.7);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(287));

	// fade-from-black
	this.instance = new lib.blackwideskyscraper();
	this.instance.parent = this;
	this.instance.setTransform(161,25.5,1.954,0.085,0,0,0,0.3,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:0.1,scaleX:1.95,scaleY:0.08,x:160.1,y:25,alpha:0},9).wait(278));

	// logo
	this.instance_1 = new lib.kalemobileleaderboard();
	this.instance_1.parent = this;
	this.instance_1.setTransform(287.4,25,0.022,0.022,0,0,0,2.3,2.3);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({regX:0,regY:0,scaleX:0.03,scaleY:0.03,x:281.9,y:23.5},0).to({regX:0.1,regY:0.1,scaleX:1.4,scaleY:1.4,y:23.6,alpha:1},6,cjs.Ease.get(1)).to({regX:0,regY:0,scaleX:1.3,scaleY:1.3,x:281.8,y:23.5},7).wait(265));

	// fill-mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AxBDIIAAkcMAkUAAAIAAEcg");
	mask.setTransform(123.5,20);

	// fill-your-inbox-with
	this.instance_2 = new lib.fillinboxmobileleaderboard();
	this.instance_2.parent = this;
	this.instance_2.setTransform(76.4,14.6);
	this.instance_2.alpha = 0;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(16).to({x:-103.1,y:15.8},0).to({x:96.4,y:14.6,alpha:1},10,cjs.Ease.get(1)).to({x:86.4},6,cjs.Ease.get(1)).wait(33).to({alpha:0},5).wait(217));

	// party-ready-mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("AxBDIIAAkcMAkUAAAIAAEcg");
	mask_1.setTransform(123.5,20);

	// party-ready-recipes
	this.instance_3 = new lib.partyreadyrecipesmobileleaderboard();
	this.instance_3.parent = this;
	this.instance_3.setTransform(79.2,31.4);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(65).to({x:-117.8,y:32.8},0).to({x:89.2,y:31.4,alpha:1},10,cjs.Ease.get(1)).to({x:79.2},6,cjs.Ease.get(1)).wait(33).to({alpha:0},5).wait(168));

	// diy-tips-mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("AxBDIIAAkcMAkUAAAIAAEcg");
	mask_2.setTransform(123.5,20);

	// diy-tips
	this.instance_4 = new lib.diytipsmobileleaderboard();
	this.instance_4.parent = this;
	this.instance_4.setTransform(39,31.4);
	this.instance_4.alpha = 0;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(114).to({x:-59.2,y:32.8},0).to({x:43.5,y:31.4,alpha:1},10,cjs.Ease.get(1)).to({x:32.5},6,cjs.Ease.get(1)).wait(33).to({alpha:0},5).wait(119));

	// holiday-mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("AxBDIIAAkcMAkUAAAIAAEcg");
	mask_3.setTransform(123.5,20);

	// holiday-inspiration
	this.instance_5 = new lib.holidayinspirationmobileleaderboard();
	this.instance_5.parent = this;
	this.instance_5.setTransform(73.9,31.4);
	this.instance_5.alpha = 0;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(163).to({x:-117.1,y:32.8},0).to({x:83.9,y:31.4,alpha:1},10,cjs.Ease.get(1)).to({x:73.9},6,cjs.Ease.get(1)).wait(33).to({alpha:0},5).wait(70));

	// delicious-mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	mask_4.graphics.p("AxBDIIAAkcMAkUAAAIAAEcg");
	mask_4.setTransform(123.5,20);

	// something-delicious
	this.instance_6 = new lib.somethingdeliciousmobileleaderboard();
	this.instance_6.parent = this;
	this.instance_6.setTransform(79.2,31.4);
	this.instance_6.alpha = 0;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(212).to({x:-125.8},0).to({x:89.2,alpha:1},10).to({x:79.2},6).wait(30).to({alpha:0},5).wait(24));

	// sign-up-mask (mask)
	var mask_5 = new cjs.Shape();
	mask_5._off = true;
	mask_5.graphics.p("AuxDIIAAkcMAiFAAAIAAEcg");
	mask_5.setTransform(123.6,20);

	// sign-up
	this.instance_7 = new lib.signupmobileleaderboard();
	this.instance_7.parent = this;
	this.instance_7.setTransform(207.6,24.3);
	this.instance_7.alpha = 0;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_5;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(258).to({x:33.7},0).to({x:229.5,alpha:1},10,cjs.Ease.get(1)).to({x:219.5},8,cjs.Ease.get(1)).wait(11));

	// rollover-mask (mask)
	var mask_6 = new cjs.Shape();
	mask_6._off = true;
	mask_6.graphics.p("AxBDrIAAmoMAkUAAAIAAGog");
	mask_6.setTransform(123.5,23.5);

	// cta-rollover
	this.cta_rollover = new lib.ctarollover();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(105.5,23.9);

	var maskedShapeInstanceList = [this.cta_rollover];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_6;
	}

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(258).to({x:-79},0).to({x:115.5},10,cjs.Ease.get(1)).to({x:105.5},8,cjs.Ease.get(1)).wait(11));

	// cta-mask (mask)
	var mask_7 = new cjs.Shape();
	mask_7._off = true;
	mask_7.graphics.p("AxBDrIAAmoMAkUAAAIAAGog");
	mask_7.setTransform(123.5,23.5);

	// cta-rectangle
	this.instance_8 = new lib.ctamobileleaderboard();
	this.instance_8.parent = this;
	this.instance_8.setTransform(105.5,23.9,1.745,1.269);
	this.instance_8.alpha = 0;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_7;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(258).to({x:-79},0).to({x:115.5,alpha:1},10,cjs.Ease.get(1)).to({x:105.5},8,cjs.Ease.get(1)).wait(11));

	// table
	this.instance_9 = new lib.mobileleaderboardtable();
	this.instance_9.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(287));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(159.9,24.9,321,51.1);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 320,
	height: 50,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/mobileleaderboardtable.jpg", id:"mobileleaderboardtable"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;