(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.whitelogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AqoZNQk7iFjyjyQjyjziFk6QiJlFAAljQAAlkCJlFQCFk6DyjzQDzjyE6iFQFFiJFjAAQFkAAFFCJQE6CFDyDyQDyDzCGE6QCJFFAAFkQAAFjiJFFQiGE6jyDzQjyDyk6CFQlFCJlkAAQljAAlFiJgALTMVIgBANQgBAOALAAIAxAAQAMAAABALIAACUQAAAHAEADQAFABAJAAQAKAAAEgBQAFgDAAgHIAAiUQgBgLAMAAIAyAAQALABAAgTQAAgRgMAAIifAAQgIAAgBAIgADSOMIBBBGQAHAJATgBQAOAAAEgEQAGgFgIgJIhOhVQgJgKAJgIIBAg7QAKgJgMgLQgMgMgNALIhKBDQgFAFgEABQgFADgLgBQgJABAAgNIAAg3QAAgMgSgBQgKAAgEACQgGADAAAIIAAC1QABAMAQAAQAVABAAgMIAAg8QAAgGAEgFQADgFAFAAQATABALAIgAhwOXQALAAAGAJIAfAxQAHAKARgBQAOAAAEgEQAFgEgFgIIgjgxQgDgGAHgHQAPgKAIgJQAPgQAAgXQAAgggVgTQgUgTggAAIhrAAQgKABABAHIAAC7QAAALAMAAIAPAAQAKgCAAgGIAAgxQgBgEAEgDQAEgDADAAgAmQOxQAHAAADAGIAOAbQADAJAPgBQAHAAAHgBQAJgEgDgGIhYi7QgEgJgMAAQgKAAgFAKIhZC5QgGAMAXAAQASAAACgIIAMgWQAFgLAJAAgArGNkIANBsQABAFAFADQAFADAFgBQAXAAgBgKIgVi2QgCgIgEgDQgDgCgGgBQgLABgEAHIg8BRQgHAIgDAAQgFgBgFgHIg5hPQgEgJgKAAQgLAAgEAFQgEADgBAJIgVCyQAAAFAGADQAFADAFgBQAUAAABgKIAPhqQAAgGAGgBQAEABACADIAtA8QAEAGAHAAQAGAAAEgFIAwg/QADgDAEgBQAFABACAGgAGyMbIAACvQAAAPAMAAICdAAQAKgBAAgQQAAgTgKAAIh6AAQgKAAAAgKIAAgfQAAgKALAAIBGAAQALAAgBgSQAAgSgKAAIhHAAQgKAAAAgJIAAgcQABgIAIgBIB6AAQAHABADgGQACgEAAgJQAAgJgCgDQgDgFgGAAIidAAQgMAAAAAOgAT4IxQgMAMAAATQAAASAMANQAOANARAAQATAAANgNQANgNAAgSQAAgTgNgMQgNgOgTAAQgRAAgOAOgAP5JKQAlAMA0AAQBUAAAzgsQAzgtgBhKQAAgggMgfQgMgegWgXQgUgVgXgSQgWgRgzgjIgqgeQgbgWgMgSQgJgLAAgXQAAgaARgPQASgQAdAAQAtAAAjAbQAOALAGAHQAHAHAOAVQAKAPAMAAQAKgBAIgFQAHgGAAgJQgBgIgBgEIgUhbQgGgZgSAAQgFABgDABIgKAGQgLAHgIAAIgMgBIgVgGQgkgIgmAAQhGAAgrAmQgrAmAAA9QAAA0AgAlQATAXASAOIBOA4QA/ArAbAdQAbAfABAhQgBAigZAVQgaAUgqAAQgkAAghgSQgigRgWgfIgMgRQgJgMgMAAQgMAAgHAHQgIAJAAALQAAAJACAIIAVBVQAFAPAFAGQAGAHALAAQAJAAALgIQAJgJAJAAIASAFgAjRF+QAHAAACALIABACQAYBeBGA2QBGA2BlABQCCgBBMhQQBMhRAAiIQAAiFhMhQQhMhQiAAAQhmAAhHA3QhGA2gYBfIgBABQgBAKgIABQgHABgCgMQgWhfhHg3QhIg3hpAAQh/AAhMBQQhLBRgBCIQAACFBNBRQBLBQB+AAQBogBBIg2QBGg2AYhfIABgCQACgKAGAAIABAAgAFmIeQgFAHAAAKQAAANAKAFQAGADAVADQBdANBrABQBGgBAwgOQAxgNAlgeQAugmAag9QAZg+AAhNQAAhFgUg4QgUg4glglQgngog0gSQg2gShPAAQhrAAhdANQgVADgGADQgKAGAAAMQAAALAFAGQAHAIAIgBIARAAQAKABAFAKQACALABAXIAAF5QgBAYgCAKQgFALgKAAIgRAAQgIAAgHAHgAyyIgQgGAGgBALQAAAOAJAFQAIAFAXAAICcAAQAXAAAKgFQAIgFABgOQgBgLgFgGQgHgIgKAAIgTAAQgMABgGgLQgCgHAAgbIAAiKQAAgZAIgGQAEgDAeAAIBGAAQAbAAAHADQAIAEACAMIAAAGQAEAWATAAQAOAAAFgJQAFgIAAgWIAAhIQAAgWgFgJQgFgJgOAAQgTAAgEAWIAAAEQgCANgIADQgHAEgbAAIhGAAQgdAAgFgDQgIgGAAgZIAAhkQgBgjAJgIQAIgJAjAAIBtAAQAgAAAMAEQAQAFAFAQQAFANAEAFQAHANAOAAQANAAAFgIQAEgJgDgRIgMg6QgFgWgaABIlvAAQgWgBgJAGQgIAFgBAOQABAKAGAHQAHAHAJAAIARAAQAEAAAEADQAEAEABAFQAEALAAAXIAAF7QAAAYgDAKQgEALgKgBIgRAAQgJAAgHAIgACnrWQADAJgKADQgoAOgmATQgmATgYATQg6AngfBDQghBDAABZQAACLBPBUQBOBUCEAAQCHAABQhUQBQhVgBiOQABikhphOQg7gsg3AGQgiAEgFATQgEAUAaAKQA2AUAZA7QAXA4AABfQAABwgqBCQgrBChJAAQhMAAgphAQgrhBAAhxQAAhRAQgyQATg/AvgvQAegdBGgjQA+geAigsQAUgZAAgVQABgTgPgFQgMgDgNAMIgYAXQgvAfg4gTQgugOglgpQgbgfgogIQgcgGggAHQgKADgDgHQgEgHALgIQAcgVAqACQAvABAfAdQAeAbAgAPQAkAQAagEQARgDAAgPQAAgOgSgGQgggMgmg2Qglgzg1gQQhPgWhJA8QhDA4gYBWQgGAXALALQANALAUgJQA6gaAvAXQAJAEAhATQAcASAWAJQAsASA7gLIAGgBQAIAAABAIgAvDlQIBJDYQAHAYALAKQALAJATAAQATAAAKgLQALgMAJgeICHm0QAHgWAHgJQAIgJALgBQAjgFAAAxIAAF9QAAAbgCAHQgBAEgFADQgEADgFAAIgRAAQgIAAgHAHQgGAHAAAKQAAAOAIAFQAIAFAWAAICbAAQAUAAAIgFQAIgFAAgNQABgLgGgHQgGgHgJAAIgQAAQgLAAgGgKQgCgKAAgYIAAiBQABgdAFgHQAGgGAXgBIB0AAQAXABAGAHQADAEABAGIABAeIAAB8QAAAbgDAHQgGAKgJAAIgQAAQgJAAgHAHQgHAHAAAKQABAOAHAFQAJAFAWAAICaAAQAWAAAJgFQAIgFAAgOQAAgKgGgHQgGgHgJAAIgSAAQgFAAgDgDQgFgDgCgEQgCgLAAgXIAAl9QAAgYACgKQACgEAFgEQADgCAFAAIASAAQAIgBAHgGQAGgHAAgLQABgOgKgFQgIgFgWAAIiaAAQgWAAgJAFQgJAFAAAOQAAALAHAHQAGAGALABIAQAAQAKAAAFAKQADAGAAAcIAABoIgBAeQgBAHgDADQgGAIgXAAIh0AAQgXAAgGgHQgFgGgBgeIAAhtQAAgaACgIQAGgKALAAIAQAAQAJgBAGgGQAGgHAAgLQAAgOgIgFQgIgFgVAAIkmAAQgRAAgIAFQgHAHgBAMQABAVAbADQAdADAAASQABAJgEAMIheE6QgBAGgFAAQgEABgCgFIhfkuQgJgZABgKQAAgLAFgGQAGgEARgCQAbgEABgTQAAgXgdAAIinAAQgeAAABAZQAAAKAFAFQAFAFAOAEQAPADAGAFQAHAEADAJIAmBvQAHAXgJAZIg+C2QgCAGgFABQgEAAgCgGIhzlHQgDgKAAgJQgBgKAHgFQAGgFAOgBQARgCAGgEQAIgFAAgLQAAgXgcAAIiwAAQgcAAAAAWQAAAKAFAGQAFAFAOACQAUAEAHAIQAHAHAKAaICmG+QAJAZAKAJQALAJATAAQAQAAANgJQAGgHALgbIBMjYQACgEAFAAQADAAACAEgAOkiCQgGAHAAAKQAAAOAIAFQAJAGAVAAIFigBQAOAAAHgFQAHgFADgLIANhCQAEgQgFgJQgGgJgLAAQgPABgJAQIgHAPQgPAfgvAAIhVAAQgjAAgPgFQgKgEgDgLQgDgLAAgiIAAhrQAAgaAIgFQAEgDAfgBIAnAAQAaABAIADQAHADACANIABAGQAEAWASgBQAOABAFgJQAGgJgBgWIAAhIQABgWgGgIQgFgJgOAAQgTAAgDAVIgBAFQgCANgHADQgHAEgbAAIgnAAQgfAAgEgEQgIgEAAgaIAAhlQAAgiAJgJQAIgJAjAAIBPAAQAgABAMADQAPAGAHAPQAFAQADADQAHANAOgBQAMAAAGgIQAEgJgDgQIgMg7QgEgVgaAAIlTAAQgVAAgJAFQgJAGAAANQAAAKAGAHQAIAIAIgBIARAAQAEABAEADQAEADABAGQAEAIAAAZIAAF8QAAAagEAIQgBAFgDADQgEADgFAAIgRAAQgIAAgHAGgAHziCQgHAHAAAKQAAAOAIAFQAIAFAWAAIE/AAQAaAAAEgVIAOhCQADgQgFgJQgFgJgMAAQgPABgIAQIgIAPQgOAfgwAAIgwAAQgaABgLgCQgLgCgHgEQgHgFgCgJQgCgJAAgdIAAlkQAAgcACgGQADgLAPAAIASAAQAJAAAHgGQAHgHgBgLQAAgNgJgGQgIgFgXAAIidAAQgWAAgJAFQgJAGAAANQABALAGAHQAHAGAKAAIAQAAQALAAADALQADAJAAAZIAAGAQAAAXgDAIQgCAEgEAEQgEADgEAAIgQAAQgKAAgFAGg");
	this.shape.setTransform(0,0,0.17,0.17);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAZQgKgKAAgPQAAgOAKgLQAKgJAOgBQAPABAKAJQAKALAAAOQAAAPgKAKQgKALgPgBQgOABgKgLgAAWAYIgPgVQANgBAAgNQAAgPgRAAIgTAAIAAAyIAJAAIAAgUIAFAAIAOAUIAKAAg");
	this.shape_1.setTransform(22.1,10,0.17,0.17);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrAiQgFAAgEgDQgEgDAAgFIAAgtQAAgLANAAIA+AAQARAAAKAJQALAJAAAPQAAAQgLAJQgKAJgRAAg");
	this.shape_2.setTransform(-1.9,14.4,0.17,0.17);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJAHIAAgNIAIAAQALAAAAAGQAAAHgNAAg");
	this.shape_3.setTransform(22.2,9.8,0.17,0.17);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhvCtQgog+AAhsQAAhuAog/QApg/BFAAQBGAAAqBAQApA+AABsQAABrgpA/QgpA/hGAAQhGAAgpg9g");
	this.shape_4.setTransform(-8.3,5.1,0.17,0.17);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYAfQgIAAADgIIAZgxQABgEADAAQADAAACAEIAZAyQABADgCACQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-7.5,14.9,0.17,0.17);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgtDtQgngDgNgHQgVgLAAghIAAljQAAghAKgMQAKgLAcgFIAdgDQBLAAAqA/QArA/AABvQAABxgrA/QgqA8hGAAIgJAAg");
	this.shape_6.setTransform(10.9,5.1,0.17,0.17);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhvCtQgog/AAhrQAAhuAog/QApg/BGAAQBFAAAqBAQApA+AABsQAABrgpA/QgpA/hGAAQhGAAgpg9g");
	this.shape_7.setTransform(1.2,5.1,0.17,0.17);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.whitelogo, new cjs.Rectangle(-29.7,-29.7,59.4,59.4), null);


(lib.somethingdeliciousmobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgEAgIgGgCIgCACIgCAAIgBAAIgCgBQgCgBgBgFQgCgGAAgEIABgDQAAAAABgBQAAAAAAAAQAAAAABAAQAAAAABgBQACAAADAGIADADQABADADABIAGACQAEgBADgCQACgCABgDQgBgGgJgEIgEgCQgJgEgEgEQgCgDAAgHQgBgHAGgFQAGgFAIgBIADABIAFAAIACgBIACAAQAEAAACAFQADAFAAAFIgBADIgCABIgDgBIgEgDQgCgEgCgCQgCgBgEgBQgCAAgDACQgCACAAAEQAAACACACQADADAHADIAAABQARAHAAAKQAAAJgGAGQgHAFgKAAg");
	this.shape.setTransform(165.1,-17.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AANAfIgBgDIAAgFIgCACIgBAAQgDADgDACQgDABgFABQgEgBgEgBQgEgCgDgDQgDgEgBgFIgBgRIAAgDIAAgFIAAgCIgBgGIgDgCIgCgBQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABgBIAFgCIAIgCIAHgBQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAAAIABAEIAAADIgBAWQAAAMADAEQACAFAGABQAHAAADgHQADgGAAgOIAAgFIgBgGIgDgCIgCgBQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAQABgBAEgCIAIgCIAHgBIACABIABAEIAAAEIgBAYIAAAKIABAEQAAADADABIABABQABAAABAAQAAAAABABQAAAAABABQAAAAAAAAIgBADIgEACIgJADIgGABIgDgBg");
	this.shape_1.setTransform(158.6,-17.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgVAXQgJgJAAgOQAAgMAJgKQAJgJANAAQANAAAJAJQAIAIAAAOQAAANgJAJQgJAKgNAAQgNAAgIgJgAgLgRQgDAFAAAIQAAALAEAIQAFAIAHAAQAGAAAEgFQADgFABgIQAAgLgGgIQgFgIgGAAQgGAAgEAFg");
	this.shape_2.setTransform(151.5,-17.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgKAsQgBgBAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABgBQAAAAABAAIABgBQABAAAAgBQABAAAAAAQAAgBABAAQAAgBAAAAIABgGIAAgFIAAgEIAAgHIgBgLIgCgEIgDgBQgDgBAAgCIABgCIADgDIAKgDIAGgBIABABIABAEIAAAEIAAACIAAAPIAAABIgBAPIABAIIACADIADABQAAAAABABQAAAAABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAABIgMABQgIAAgDgBgAgHgeQgCgCAAgDQAAgDACgDQAEgDADABQAEAAACABQADADAAAEQAAADgDACQgDADgDAAQgEAAgDgDg");
	this.shape_3.setTransform(146.1,-18.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgTAXQgIgJAAgNQAAgNAJgJQAJgKANAAQAKAAAHAGQAHAFAAAHQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQgCACgDAAQgDAAgCgBQgCgCgCgFQgCgEgCgCQgDgCgDAAQgGAAgEAGQgEAFAAAJQAAAKAFAHQAGAHAIAAIAGgBIAFgCIACgCQADgDACAAIACABIABACIgCAEIgDAEQgFAEgFACQgFACgGAAQgMAAgJgJg");
	this.shape_4.setTransform(141.1,-17.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgKAsQgBgBAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABgBQAAAAABAAIACgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAgBAAAAIAAgGIAAgFIAAgEIAAgHIAAgLIgCgEIgCgBQgFgBAAgCIACgCIAEgDIAJgDIAGgBIACABIABAEIAAAEIAAACIgBAPIAAABIAAAPIAAAIIACADIACABQABAAABABQAAAAABAAQAAABAAAAQABABAAAAQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBABIgLABQgIAAgDgBgAgHgeQgCgCAAgDQAAgDACgDQADgDAEABQAEAAADABQACADAAAEQAAADgDACQgDADgDAAQgEAAgDgDg");
	this.shape_5.setTransform(136,-18.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgJAsQgBAAgBgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABgBABAAIACgCIACgEIAAgMIAAgKIAAgKIAAgFIgBgUIgBgFIgEgBQgEgBAAgDQAAAAAAAAQAAgBAAAAQABAAAAgBQAAAAAAAAIAGgDIAIgCIAGgBIACABIABAEIAAAFIgBArIABAVIABAFIADACQABAAAAABQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAABgBAAQAAABgBAAIgLABQgJAAgCgBg");
	this.shape_6.setTransform(132.3,-18.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgTAXQgJgJAAgNQAAgNAJgJQAJgKANAAQAMAAAHAHQAHAHAAALIgBAFIgGABIgXAAIgDgBIgBgCIABgDIADgBIAMAAIADAAIABgCQAAgGgEgEQgEgEgFAAQgHAAgDAGQgEAHAAAJQAAAIAFAHQAFAHAHAAIAHgBIAGgDIACgCIAFgCIACABIABACIgBAEIgEAEQgGAEgFACQgEACgGAAQgMAAgJgJg");
	this.shape_7.setTransform(127.3,-17.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgMAsIgIAAIgFAAIgFAAIgKgBQAAgBgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABAAQAAgBABAAIAEgCQABgCAAgJIABgXIgBgWQAAgJgBgCIgEgCQgDgBAAgDQAAAAAAgBQAAAAAAgBQABAAAAAAQABgBAAAAIAKgBIAGAAIAGAAIAIAAIAHAAQAWAAAMAMQAMALAAAVQAAAVgMALQgNALgXAAgAgMgiQgBAAgBABQAAAAgBAAQAAABAAAAQgBABAAAAIgBAJIgBATIABAWIABAMQABACAEABIAJABQAOAAAHgIQAHgJAAgRQAAgRgIgJQgIgKgPAAIgHABg");
	this.shape_8.setTransform(119.1,-18.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgVAoQgJgFABgGQgBgEACgCQACgBADAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIACAEQACAEAEADQADADAIAAQAHAAAGgEQAFgDAAgEQAAgBAAAAQAAgBAAgBQgBAAAAgBQAAAAgBAAQgCgCgEAAIgHABIgIAAQgLAAgGgEQgGgDAAgGQAAgDACgCQACgDAFgCQgEgDgCgEQgCgEAAgFQAAgKAIgGQAHgHAMAAIAGABIAJABIAFgBIAGgDIACACIABABQAAADgCADIgFAEIACAFIAAAEQAAALgIAGQgHAGgLAAIgHgBIgFgBIgCACIgBACQAAABABABQAAAAAAABQAAAAABABQAAAAABAAQADACAGAAIAJAAIAJgCQAIAAAFAEQAFAEAAAGQAAAKgKAHQgKAFgNAAQgMABgHgFgAgJgeQgEAEABAGQgBAHAEAEQADADAFABQAEgBADgDQAEgEAAgGQAAgHgEgEQgCgDgFAAQgFAAgDADg");
	this.shape_9.setTransform(107.8,-16.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAIAeQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAABAAIADgBIACgEIAAgJQAAgTgCgEQgDgFgGAAQgDAAgDACQgDACgBADIgCAHIgBAQIABAIQAAAAAAABQAAAAABAAQAAABAAAAQAAAAABABIACABQABAAABAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAABQgBAAgBAAIgLABQgJAAgDgBQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABgBIABAAQABgBAAAAQABAAAAgBQAAAAAAAAQABgBAAAAIAAgHIAAgEIAAgFIAAgFIAAgNIgCgDIgDgBQgEgBAAgDIACgCIADgCIAJgDIAGgBIADABIABADIAAAEIAAABIAAAAIABAAIAAgBIABgBIABgBQAHgGAHAAQAEAAAEACIAHAFIAEAIIABAOIAAAIIAAAEIAAADIABAGIACADIACAAQAAABABAAQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBABQgBAAAAAAIgMABQgJAAgDgBg");
	this.shape_10.setTransform(100.5,-17.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgKAsQgBgBAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABgBQAAAAABAAIABgBQABAAAAgBQABAAAAAAQAAgBABAAQAAgBAAAAIABgGIAAgFIAAgEIAAgHIgBgLIgBgEIgEgBQgDgBAAgCIABgCIADgDIAKgDIAFgBIACABIABAEIAAAEIAAACIAAAPIAAABIgBAPIABAIIACADIADABQAAAAABABQAAAAABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAABIgLABQgJAAgDgBgAgGgeQgDgCAAgDQAAgDADgDQADgDADABQAEAAACABQADADAAAEQAAADgDACQgDADgDAAQgEAAgCgDg");
	this.shape_11.setTransform(95,-18.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAJAsQgBAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBABAAIACgBQAAAAAAAAQABgBAAAAQAAgBAAAAQABgBAAAAIAAgJQAAgUgCgEQgCgFgHAAQgCAAgDACQgDACgCACQgBADgBAFIAAAQIAAAIIACADIACABQABAAABABQAAAAABABQAAAAABABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAABgBAAIgLABQgKAAgDgBQgBAAAAgBQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAgBABAAIACgBIACgDIABgJIAAgKIAAgKIgBgaQAAgHgBgBIgEgCQgBgBgBAAQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIAHgDIAGgCIAFgBIADABIABAEIAAADIAAAYIAAADIAAACIABAAIABgBIACgDQADgDADgBIAHgCQAKAAAGAHQAFAHAAANIAAAFIAAALIAAAEIAAAEIACACIACABQABAAAAABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAABgBAAQgDABgKAAIgKgBg");
	this.shape_12.setTransform(89.3,-18.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgCAlIgGgEIgDgEIAAgNIAAggIgGAAIgCAAIgBgCIAAgCQABgBAGgGIACgCIADgCQAGgGACABIABAAIABACIAAALIAOAAIACAAIAAACIAAACIAAADIgCAAIgNAAIAAABIgBABIAAAdQAAAIACACQAAAAAAABQABAAAAAAQABABAAAAQABAAABAAIAFgBIAEgBIACABIACACQAAAEgGADQgFADgGAAIgGgBg");
	this.shape_13.setTransform(83.5,-17.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgTAXQgJgJAAgNQAAgNAJgJQAJgKANAAQAMAAAHAHQAHAHAAALIgBAFIgGABIgXAAIgDgBIgBgCIABgDIADgBIAMAAIADAAIABgCQAAgGgEgEQgEgEgFAAQgHAAgDAGQgEAHAAAJQAAAIAFAHQAFAHAHAAIAHgBIAGgDIACgCIAFgCIACABIABACIgBAEIgEAEQgGAEgFACQgEACgGAAQgMAAgJgJg");
	this.shape_14.setTransform(77.9,-17.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAbAeQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQAAgCADgCIACgBQABAAAAAAQAAAAABgBQAAAAAAgBQAAAAABgBIAAgLQAAgRgCgFQgDgEgGAAQgHAAgEAGQgCAGAAAOIAAADQAAAHAAACIACADIACAAQABABAAAAQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAgBABQAAAAgBAAQgDABgJAAIgKgBQgBAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAABgBQAAAAAAgBQABAAAAgBQABAAABAAIACgBQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBIAAgJQAAgTgCgEQgDgFgGAAQgDAAgDACQgDACgBADIgCAIIgBAPIABAIIACADIABABQABAAABAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAABQgBAAgBAAIgKABIgMgBQgBAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQABAAABgBIABAAIACgDIABgHIAAgEIgBgFIAAgDIAAgOIgBgEIgEgBQAAAAgBgBQgBAAAAgBQgBAAAAgBQAAAAAAgBIABgCIAEgCIAJgDIAGgBIADABIAAADIAAADIAAABIABABIAAAAIABgBIABgBIABAAQAHgHAHAAIAFABIAGACIADAEIADADIADgCIACgCQAFgEADgBQACgBAEAAQAHAAAFADQAFADADAFQADAFgBARIAAAGIAAAEIAAACIABAFIADADIABAAQABABAAAAQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAgBABQAAAAgBAAQgDABgKAAIgLgBg");
	this.shape_15.setTransform(68.9,-17.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgVAXQgJgJAAgOQAAgMAJgKQAJgJANAAQANAAAJAJQAIAIAAAOQAAANgJAJQgJAKgNAAQgNAAgIgJgAgLgRQgEAFABAIQAAALAEAIQAGAIAGAAQAGAAAEgFQADgFAAgIQAAgLgEgIQgGgIgGAAQgGAAgEAFg");
	this.shape_16.setTransform(59.8,-17.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgOAsQgHgBgEgDQgDgCgBgFQgCgFAAgGIABgFQAAAAABgBQAAAAAAAAQABAAAAAAQABgBAAAAQADABADAFIACACQADAIAFACQAFADAGAAQAGAAAEgEQAFgDAAgGQAAgIgRgJIgCgBQgPgFgFgFQgFgGAAgJQAAgKAIgIQAIgGANgBIAHABIAIACIADgCIACAAIACABIADADIADAIIABAHIgBADIgCABQgEAAgDgEIgBgCQgDgEgEgCQgEgCgFAAQgGAAgEADQgEADAAAGQAAAFADADQADADANAGIACABQALAFAFADQADADACAEIACAJQAAAMgJAIQgJAGgOAAQgIAAgGgBg");
	this.shape_17.setTransform(52.6,-18.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.somethingdeliciousmobileleaderboard, new cjs.Rectangle(46.9,-27.8,123.2,18.5), null);


(lib.signupmobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNAiQgFgCgFgFIAIgHQACAEAFACQAEADAEAAIAEgBIAGgCIACgEQACgCAAgEQAAgDgCgCIgDgEIgGgCIgFgCIgGgDIgHgCIgDgGQgCgDgBgFQAAgFADgEQACgEADgDQAEgCAEgBIAIgBIAGAAIAFACQAGACADAEIgGAHIgHgFQgDgCgFAAIgDABIgFACIgDADQgBACAAADQAAADABACIADAEIAFACIAEACIAHACIAHADQADACACAEQACADAAAGQAAAFgCAEQgCAEgDADIgIAEIgJABQgGAAgHgDg");
	this.shape.setTransform(-99.6,8.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUAkIAAhHIAKAAIAAA+IAfAAIAAAJg");
	this.shape_1.setTransform(-104.7,8.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgEAkIAAhHIAJAAIAABHg");
	this.shape_2.setTransform(-109.2,8.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAYAkIgIgSIggAAIgHASIgLAAIAehHIAIAAIAfBHgAANAJIgNggIgNAgIAaAAg");
	this.shape_3.setTransform(-114.3,8.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAbAkIAAg7IAAAAIgYA7IgFAAIgXg7IgBAAIAAA7IgJAAIAAhHIAPAAIAUA2IABAAIAUg2IAQAAIAABHg");
	this.shape_4.setTransform(-122.5,8.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgWAkIAAhHIAsAAIAAAKIgjAAIAAAUIAhAAIAAAIIghAAIAAAYIAkAAIAAAJg");
	this.shape_5.setTransform(-130,8.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AANAkIgRggIgKAAIAAAgIgKAAIAAhHIAXAAQAEABAEABIAIADQAEACACAEQACAEAAAFQAAAIgFAFQgCACgEABIgGACIATAhgAgOgEIALAAIAGAAIAFgCQAAAAABgBQAAAAABAAQAAgBABAAQAAgBAAAAQACgDAAgDQAAgDgCgCIgDgEIgFgBIgFgBIgMAAg");
	this.shape_6.setTransform(-138.9,8.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgHAkIgHgCQgHgCgFgFQgFgFgDgHQgCgHAAgIQAAgIACgGQADgHAFgFQAFgFAHgDIAHgCIAHAAQAIAAAHACIAGAEIAGAEQAFAFADAHQACAGAAAIQAAAIgCAHQgDAHgFAFIgGAEIgGADQgHADgIAAIgHgBgAgKgZQgFACgDAEQgEAEgCAFQgCAFAAAFQAAAGACAFQACAFAEAEQADAEAFACQAFACAFAAQAGAAAFgCQAFgCADgEQAEgEACgFQACgFAAgGQAAgFgCgFQgCgFgEgEQgDgEgFgCQgFgDgGAAQgFAAgFADg");
	this.shape_7.setTransform(-146.6,8.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgVAkIAAhHIArAAIAAAKIghAAIAAAVIAfAAIAAAIIgfAAIAAAgg");
	this.shape_8.setTransform(-153.7,8.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgXAkIAAhHIAWAAQAFABAEABQAFABAEADQADACABADQADAEAAAFQAAAGgDADQgBAFgEABIgIADIgJABIgLAAIAAAggAgMgDIAKAAIAFgBIAGgCIADgDIACgGQAAgDgCgCIgDgEIgGgBIgFgBIgKAAg");
	this.shape_9.setTransform(-162.4,8.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgGAjIgFgBIgFgDIgDgEQgEgDgCgGQgBgFAAgFIAAgsIAKAAIAAAsIAAAHIADAGQACADAEACQADABAEAAQAFAAAEgBQADgCACgDIADgGIABgHIAAgsIAKAAIAAAsIgCAKQgCAGgDADIgEAEIgFADIgFABIgHABIgGgBg");
	this.shape_10.setTransform(-169.3,8.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AARAkIgkg6IAAA6IgKAAIAAhHIANAAIAkA4IAAg4IAKAAIAABHg");
	this.shape_11.setTransform(-179.6,8.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgJAiQgHgCgFgFQgFgFgCgHQgDgHAAgIQAAgIADgGQACgHAGgFIAFgEIAGgEQAHgCAHAAIAIAAIAIACQAGADAFAEIgHAHQgDgDgFgDIgGgBIgFgBQgGAAgFADQgFACgDAEQgEAEgCAFQgBAFAAAFQAAAGABAFQACAFAEAEQADAEAFACQAFACAGAAIAJgBIAHgCIAAgUIgPAAIAAgHIAZAAIAAAhQgFADgHABIgOACQgIAAgHgDg");
	this.shape_12.setTransform(-187.7,8.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgEAkIAAhHIAJAAIAABHg");
	this.shape_13.setTransform(-193,8.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgNAiQgFgCgFgFIAIgHQADAEAEACQAEADAEAAIAEgBIAGgCIACgEQACgCAAgEQAAgDgCgCIgDgEIgGgCIgFgCIgGgDIgGgCIgFgGQgCgDAAgFQABgFACgEQACgEADgDQAEgCAEgBIAIgBIAGAAIAFACQAGACADAEIgHAHIgFgFQgEgCgEAAIgFABIgEACIgDADQgCACAAADQAAADACACIADAEIAEACIAFACIAIACIAGADQADACACAEQACADAAAGQAAAFgCAEQgCAEgEADIgHAEIgJABQgGAAgHgDg");
	this.shape_14.setTransform(-197.4,8.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.signupmobileleaderboard, new cjs.Rectangle(-202.4,-0.2,108,16.3), null);


(lib.partyreadyrecipesmobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgDAgIgHgBIgCABIgCAAIgBAAIgCgBQgBgCgCgFQgCgEAAgFIABgDQAAAAABgBQAAAAAAAAQAAAAABAAQAAAAAAAAQADAAAEAEIACAEQABACAEACIAFABQAEAAADgBQACgDAAgDQABgGgKgEIgDgCQgKgFgEgDQgDgEAAgFQABgJAFgFQAGgEAIAAIAEAAIAEAAIADAAIACgBQACAAADAFQAEAFAAAFIgBAEIgEAAIgCAAIgDgFQgCgEgDgBQgDgBgDAAQgCAAgCACQgDABAAADQAAAEADABQABADAHAEIABAAQARAIAAAKQAAAIgHAFQgGAGgKAAg");
	this.shape.setTransform(165.1,-17.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgTAXQgJgJAAgNQAAgNAJgJQAJgKANAAQAMAAAHAHQAHAHAAALIgBAFIgGABIgXAAIgDgBIgBgCIABgDIADgBIAMAAIADAAIABgCQAAgGgEgEQgEgEgFAAQgHAAgDAGQgEAHAAAJQAAAIAFAHQAFAHAHAAIAHgBIAGgDIACgCIAFgCIACABIABACIgBAEIgEAEQgGAEgFACQgEACgGAAQgMAAgJgJg");
	this.shape_1.setTransform(159.1,-17.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgdAqQgDgBAAgDQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAABAAIACgCQACgBAAgFIABgUIAAgJIgBgVQAAgFgCgBIgCgBQgBAAgBAAQgBgBAAAAQgBgBAAAAQAAgBAAAAIABgDIADgBIAJgDIAHgBIACABIAAADIAAADIAAABIABAAIACgBIADgCIAGgEIAHgCQAMAAAGAJQAIAIAAANQAAAOgJAJQgHAKgNAAQgFAAgBgCQgBAAAAgBQgBAAAAAAQAAgBAAgBQAAAAAAgBIABgCIACgBIABAAIADABQAGAAAEgGQAEgGAAgIQAAgLgEgGQgFgGgGAAQgGAAgEADQgEAEAAAJIAAAmIABAGIABADIAEACIACAAIABACIABABQAAADgEABIgMABIgMgBg");
	this.shape_2.setTransform(151.9,-16.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgKArQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAQAAAAABgBQAAAAABgBQAAAAABgBIABAAQABAAAAgBQABAAAAAAQAAgBABAAQAAAAAAgBIABgHIAAgDIAAgGIAAgGIgBgMIgCgDIgDgBQgDgBAAgDIABgCIADgCIAKgDIAGgBIABABIABAEIAAAEIAAADIAAAOIAAAAIgBAPIABAJIACADIADABQAAAAABABQAAAAABAAQAAABAAAAQABABAAABQAAAAgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgMABQgIAAgDgBgAgHgeQgCgCAAgDQAAgEACgCQAEgDADAAQAEABACACQADACAAADQAAAEgDACQgDADgDgBQgEABgDgDg");
	this.shape_3.setTransform(146.5,-18.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgTAXQgIgJAAgNQAAgNAJgJQAJgKANAAQAKAAAHAGQAHAFAAAHQAAAAAAABQAAABAAAAQAAABgBAAQAAABgBAAQgCACgDAAQgDAAgCgBQgCgCgCgFQgCgEgCgCQgDgCgDAAQgGAAgEAGQgEAFAAAJQAAAKAFAHQAGAHAIAAIAGgBIAFgCIACgCQADgDACAAIACABIABACIgCAEIgDAEQgFAEgFACQgFACgGAAQgMAAgJgJg");
	this.shape_4.setTransform(141.5,-17.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgTAXQgJgJAAgNQAAgNAJgJQAJgKANAAQAMAAAHAHQAHAHAAALIgBAFIgGABIgXAAIgDgBIgBgCIABgDIADgBIAMAAIADAAIABgCQAAgGgEgEQgEgEgFAAQgHAAgDAGQgEAHAAAJQAAAIAFAHQAFAHAHAAIAHgBIAGgDIACgCIAFgCIACABIABACIgBAEIgEAEQgGAEgFACQgEACgGAAQgMAAgJgJg");
	this.shape_5.setTransform(135,-17.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AANAeQgFgTgFgEQgDgEgGAAQgFAAAAgDQAAgBAAgBQAAAAABgBQAAAAABgBQABAAABAAQAJAAAFgEQAFgEAAgIQAAgIgFgEQgFgEgIAAIgHAAQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAAAABIgBAFIAAAMIAAAaIAAATQAAAEACABIACABQAEACAAACQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBABIgMABIgOgBQAAgBgBAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAgCAEgCIADgBQABgBABgIIAAgZIAAgXQgBgJgBgBIgEgCQAAgBgBAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQABAAAAAAIAGgBIANAAIANgBIAIAAQANAAAIAGQAGAGABAKQAAAIgFAGQgFAGgIACIAAABQAHABADAEQAEAEADAKIACAGQABAJAEAAIACAAIADAAIABABIABACQAAADgDACQgEACgFAAQgNAAgEgPg");
	this.shape_6.setTransform(127.4,-18.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgcAoQgCgCAAgEQAAgDACgCQACgDADAAIADABIABABIADACIACADQADAAAEgFQADgEAAgFQAAgFgFgKIgBgBIgJgVIgFgMQgCgCgEgBIgCgCIgBgCQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABgBIAMgBIANABQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAIAAACIgBABIgCABQgBAAgBABQAAAAAAAAQgBABAAAAQAAAAAAAAIACAFIAEAMIAFAMQAAAAAAABQABABAAAAQAAAAAAABQABAAAAAAIACgDIAEgKIAEgMIACgGQAAgCgDgCQgBAAgBgBQgBAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAIAKgBIAKABQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQgBABAAAAIgDAAQgDACgEALIgCAEIgIATQgKAZgFAIQgHAIgJAAQgEAAgEgDg");
	this.shape_7.setTransform(116.1,-15.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgaAlQgHgIAAgOQAAgOAIgJQAJgJAMAAIAEAAIADACIABADQAAADgEAAIgBAAIgCAAQgGAAgEAGQgEAEAAAKQgBAKAFAHQAEAGAHAAQAFAAAEgDQADgEABgHIAAgRIAAgbIgBgGIgDgCIgCgBQgBAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAIAGgDIAHgBIAFgBIADABIABAEIAAADIgBAlIABAZQAAAGACABIAEABQAAAAABABQABAAAAAAQABABAAAAQAAABAAAAQAAADgJADIgGABIgFABIgCgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAgDIAAgBIAAgBIgCACIgDACQgDADgDABQgDABgEAAQgMAAgHgIg");
	this.shape_8.setTransform(109.5,-18.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AALAcIgDgCIgDABQgHAFgHAAQgJAAgGgFQgFgFAAgJQAAgJAHgFQAHgFANgBIAEABQAAABAAAAQABAAAAAAQAAABAAAAQAAABAAABQAAACgDAAQgGAAgEADQgEADAAAFQAAAFAEADQADADAFAAQAFAAADgDQACgDAAgGIAAgWQAAgFgCgDQgCgEgEAAQgDABgCABIgFAEIgCABQgDAFgEABQgBAAAAgBQgBAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAgBAAAAQAAgGAHgEQAHgEALAAQAGAAAFACQAFABADAEQACADAAADIABAMIAAATIABAFIACACIABABQABAAABABQABAAAAAAQABABAAAAQAAAAAAABQAAADgEACQgEADgFAAQgDAAgDgEg");
	this.shape_9.setTransform(102.2,-17.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgTAXQgJgJAAgNQAAgNAJgJQAJgKANAAQAMAAAHAHQAHAHAAALIgBAFIgGABIgXAAIgDgBIgBgCIABgDIADgBIAMAAIADAAIABgCQAAgGgEgEQgEgEgFAAQgHAAgDAGQgEAHAAAJQAAAIAFAHQAFAHAHAAIAHgBIAGgDIACgCIAFgCIACABIABACIgBAEIgEAEQgGAEgFACQgEACgGAAQgMAAgJgJg");
	this.shape_10.setTransform(95.5,-17.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAOAeQgHgTgEgEQgDgEgHAAQgEAAAAgDQAAgBAAgBQAAAAABgBQAAAAABgBQABAAAAAAQAKAAAFgEQAFgEAAgIQAAgIgFgEQgFgEgJAAIgGAAQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAgBABIAAAFIgBAMIAAAaIABATQAAAEABABIADABQAEACAAACQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAABIgOABIgMgBQgBgBgBAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAgCAEgCIACgBQACgBAAgIIABgZIgBgXQAAgJgBgBIgDgCQgBgBgBAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAIAFgBIAOAAIAMgBIAJAAQANAAAIAGQAGAGAAAKQABAIgFAGQgFAGgIACIAAABQAGABAEAEQAEAEACAKIACAGQADAJADAAIACAAIADAAIACABIAAACQAAADgDACQgDACgHAAQgLAAgEgPg");
	this.shape_11.setTransform(87.9,-18.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgLAGIgDAAIgBgDIABgDIABgCIACgDIADAAIAEAAIAEAAIAKAAIACAAIADAAIABADQAAACgCADQgCADgDAAIgDAAIgEAAIgMAAIgBAAg");
	this.shape_12.setTransform(81.2,-17.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgcAoQgCgCAAgEQAAgDACgCQACgDADAAIADABIABABIACACIADADQADAAADgFQAEgEAAgFQAAgFgFgKIgBgBIgJgVIgGgMQgBgCgDgBIgDgCIgBgCQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABgBIAMgBIANABQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAIAAACIgBABIgDABQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAAAAAIABAFIAGAMIADAMQABAAAAABQABABAAAAQAAAAAAABQABAAAAAAIACgDIAEgKIAFgMIABgGQAAgCgDgCQgBAAgBgBQgBAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAIAKgBIAKABQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQgBABAAAAIgDAAQgDACgEALIgCAEIgIATQgKAZgFAIQgHAIgJAAQgFAAgDgDg");
	this.shape_13.setTransform(75.9,-15.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgCAkIgGgDIgDgFIAAgMIAAggIgGAAIgCgBIAAgBIAAgCQAAgCAGgFIACgCIADgCQAGgFACgBIABABIABABIAAAMIAOAAIACABIAAACIAAABIAAACIgCABIgNAAIAAAAIgBACIAAAdQAAAIACACQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAIAFgBIAEgBIACABIACACQAAADgGADQgFADgGAAIgGgBg");
	this.shape_14.setTransform(70.5,-17.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgSAeQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAIACgBIACgDIAAgHIAAgEIAAgFIAAgDIAAgOIgBgEIgDgBQgBgBgBAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIABgCIAEgCIAIgDIAFgBQADAAABAIIAAACIAAAAQADgFADgDQAEgCADAAQAFAAACACQADADAAAEQAAAEgCADQgCACgEAAIgDAAIgCgCIgBgCQgBgBAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAQgEAAgCAGQgBAGAAARIABAIQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAIACAAQAEACAAACQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAIgLABQgJAAgDgBg");
	this.shape_15.setTransform(65.9,-17.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AALAcIgDgCIgDABQgHAFgHAAQgJAAgGgFQgFgFAAgJQAAgJAHgFQAHgFANgBIAEABQAAABAAAAQABAAAAAAQAAABAAAAQAAABAAABQAAACgDAAQgGAAgEADQgEADAAAFQAAAFAEADQADADAFAAQAFAAADgDQACgDAAgGIAAgWQAAgFgCgDQgCgEgEAAQgDABgCABIgFAEIgCABQgDAFgEABQgBAAAAgBQgBAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAgBAAAAQAAgGAHgEQAHgEALAAQAGAAAFACQAFABADAEQACADAAADIABAMIAAATIABAFIACACIABABQAEABAAACQAAADgEACQgEADgFAAQgDAAgDgEg");
	this.shape_16.setTransform(60,-17.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgfArQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAgDAEgBIACgCQACgBAAgHIABgaIgBgXQAAgIgBgCIgEgCQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABgBIAFgBIAHAAIAHAAIAMAAIAJAAQAOAAAGAGQAHAFAAAMQAAANgIAHQgJAFgQAAQgFAAAAgEQAAgDAEAAQAIAAAFgEQAFgEAAgJQAAgJgFgEQgFgEgJAAIgGABIgDACIAAAGIgBANIAAAaIABARIABAFIADACQAEABAAADQAAAAAAABQgBAAAAABQgBAAAAABQgBAAgBAAIgNABIgNgBg");
	this.shape_17.setTransform(53,-18.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.partyreadyrecipesmobileleaderboard, new cjs.Rectangle(47,-27.8,123,18.5), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.kalebackground = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0D6E47").s().p("A6bFUIAAqnMA04AAAIAAKng");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.kalebackground, new cjs.Rectangle(-169.2,-34,338.5,68), null);


(lib.holidayinspirationmobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAIAeQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAABAAIADgBIACgEIAAgJQAAgTgCgEQgDgFgGAAQgDAAgDACQgDACgBADIgCAHIgBAQIABAIQAAAAAAABQAAAAABAAQAAABAAAAQAAAAABABIACABQABAAABAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAABQgBAAgBAAIgLABQgJAAgDgBQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABgBIABAAQABgBAAAAQABAAAAgBQAAAAAAAAQABgBAAAAIAAgHIAAgEIAAgFIAAgFIAAgNIgCgDIgDgBQgEgBAAgDIACgCIADgCIAJgDIAGgBIADABIABADIAAAEIAAABIAAAAIABAAIAAgBIABgBIABgBQAHgGAHAAQAEAAAEACIAHAFIAEAIIABAOIAAAIIAAAEIAAADIABAGIACADIACAAQAAABABAAQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBABQgBAAAAAAIgMABQgJAAgDgBg");
	this.shape.setTransform(160.6,-17.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgVAXQgJgJAAgOQAAgMAJgKQAJgJANAAQANAAAJAJQAIAIAAAOQAAANgJAJQgJAKgNAAQgNAAgIgJgAgLgRQgEAFABAIQAAALAEAIQAGAIAGAAQAGAAAEgFQADgFAAgIQAAgLgEgIQgGgIgGAAQgGAAgEAFg");
	this.shape_1.setTransform(153.4,-17.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgKAsQgBgBAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABgBQAAAAABgBIABAAQABAAAAgBQABAAAAAAQAAgBABAAQAAgBAAAAIABgGIAAgFIAAgEIAAgHIgBgLIgCgEIgDgBQgDgBAAgCIABgCIADgDIAKgDIAGgBIABABIABAEIAAAEIAAACIAAAPIAAAAIgBAQIABAIIACADIADABQAAAAABABQAAAAABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAABIgLABQgJAAgDgBgAgGgeQgDgCAAgDQAAgEADgCQADgCADgBQAEAAACACQADADAAAEQAAADgDACQgDACgDABQgEgBgCgCg");
	this.shape_2.setTransform(148,-18.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgCAlIgGgDIgCgGIgBgMIAAggIgGAAIgCAAIAAgCIAAgBQgBgDAHgFIADgCIACgCQAGgGACABIABAAIABACIAAALIAOAAIACAAIABACIAAACIgBADIgCAAIgNAAIgBAAIAAACIAAAeQAAAHABACQABAAAAABQABAAAAAAQABABAAAAQABAAABAAIAFgBIAFgBIABABIABACQABADgGAEQgFACgHAAIgFAAg");
	this.shape_3.setTransform(144,-17.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AALAdIgDgEIgDACQgHAFgHAAQgJAAgGgGQgFgEAAgJQAAgJAHgFQAHgGANABIAEABQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAADgDAAQgGAAgEADQgEADAAAFQAAAFAEADQADADAFAAQAFAAADgDQACgCAAgHIAAgWQAAgGgCgDQgCgCgEAAQgDgBgCACIgFAEIgCACQgDAEgEAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAgBAAgBQAAgFAHgEQAHgEALAAQAGAAAFACQAFACADADQACACAAAEIABANIAAASIABAGIACACIABAAQAEABAAACQAAADgEADQgEACgFAAQgDAAgDgDg");
	this.shape_4.setTransform(138.4,-17.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgSAeQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAIACgBIACgDIAAgHIAAgEIAAgFIAAgDIAAgOIgCgEIgCgBQgBAAgBgBQgBAAAAgBQgBAAAAgBQAAAAAAgBIABgCIAEgCIAIgDIAFgBQAEAAAAAIIAAACIAAAAQADgFAEgDQADgCADAAQAEAAADACQADADAAAEQAAAEgCADQgCACgDAAIgEAAIgCgCIgBgCQgBgBAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQgEAAgCAGQgBAGAAARIABAIQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAABIADAAQADACABACQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAIgMABQgJAAgDgBg");
	this.shape_5.setTransform(132.7,-17.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgKAsQgBgBAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABgBQAAAAABgBIABAAQABAAAAgBQABAAAAAAQAAgBABAAQAAgBAAAAIABgGIAAgFIAAgEIAAgHIgBgLIgBgEIgEgBQgDgBAAgCIABgCIADgDIAKgDIAFgBIACABIABAEIAAAEIAAACIAAAPIAAAAIgBAQIABAIIACADIADABQAAAAABABQAAAAABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAABIgLABQgJAAgDgBgAgGgeQgDgCAAgDQAAgEADgCQACgCAEgBQAEAAACACQADADAAAEQAAADgDACQgDACgDABQgEgBgCgCg");
	this.shape_6.setTransform(128.3,-18.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgdAqQgBgBAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAEgCQABgBABgFIAAgUIAAgJIAAgVQgBgFgBgBIgEgBQAAAAgBAAQgBgBAAAAQgBgBAAAAQAAgBAAAAIABgDIADgBIAJgDIAGgBIADABIAAADIAAADIAAABIABAAIADgBIABgCIAHgEIAHgCQALAAAIAJQAHAIAAANQAAAOgIAJQgIAKgNAAQgFAAgBgCQgBAAAAgBQgBAAAAgBQAAAAAAgBQgBAAAAgBIABgCIADgBIABAAIACABQAHAAAEgGQAEgGAAgIQAAgLgEgGQgFgGgHAAQgFAAgDADQgEAEgBAJIAAAmIABAGIABADIADACIADAAIABACIABABQAAADgEABIgMABIgMgBg");
	this.shape_7.setTransform(122.6,-16);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgEAgIgGgCIgCACIgCAAIgBAAIgBgBQgCgBgCgFQgCgGAAgEIABgDQAAAAABgBQAAAAAAAAQAAAAABAAQAAgBABAAQADAAACAGIADADQACADADABIAGACQAEAAACgDQACgCABgDQAAgFgKgFIgEgCQgJgEgDgDQgDgFgBgGQAAgIAGgFQAFgEAJgBIADABIAFABIADgCIABAAQAEAAADAFQACAFAAAFIgBADIgCACIgDgCIgEgEQgCgDgCgCQgCgBgEgBQgDAAgCACQgCADAAACQAAADACADQADACAGADIABABQARAIAAAJQAAAJgGAGQgHAFgKAAg");
	this.shape_8.setTransform(116.3,-17.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAIAeQAAAAgBAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQABAAAAAAIADgBIACgEIAAgJQAAgTgCgEQgDgFgGAAQgDAAgDACQgDACgBADIgCAHIgBAQIABAIQAAAAAAABQAAAAABAAQAAABAAAAQAAAAABABIACABQABAAABAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAABQgBAAgBAAIgLABQgJAAgDgBQgBAAgBAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABgBIABAAQABgBAAAAQABAAAAgBQAAAAAAAAQABgBAAAAIAAgHIAAgEIAAgFIAAgFIAAgNIgCgDIgDgBQgEgBAAgDIACgCIADgCIAJgDIAGgBIADABIABADIAAAEIAAABIAAAAIABAAIAAgBIABgBIABgBQAHgGAHAAQAEAAAEACIAHAFIAEAIIABAOIAAAIIAAAEIAAADIABAGIACADIACAAQAAABABAAQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBABQgBAAAAAAIgMABQgJAAgDgBg");
	this.shape_9.setTransform(109.9,-17.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgMArQgBAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAAAQAAgDAFgCIACgBQACgBAAgIIAAgZIAAgXQAAgIgCgCIgDgCQgEgBAAgDQAAAAABgBQAAAAAAgBQABAAAAAAQABgBABAAQACgBAKAAQALAAADABQAAAAABABQAAAAABAAQAAABAAAAQABABAAAAQAAADgEABIgDACQgBABgBAFIgBAVIABAcQABALAAAAIAEACQADACABADQgBAAAAABQAAAAAAABQgBAAAAAAQgBABgBAAIgNABIgMgBg");
	this.shape_10.setTransform(104.1,-18.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgcAoQgCgCAAgEQAAgDACgCQACgDADAAIADABIABABIADACIACADQADAAAEgFQADgEAAgFQAAgFgFgKIgBgBIgJgVIgFgMQgCgCgEgBIgCgCIgBgCQAAgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAIAMgBIANABQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAIAAACIgBABIgCABQgBAAgBABQAAAAAAAAQgBAAAAABQAAAAAAAAIACAFIAEAMIAFAMQAAABAAAAQABABAAAAQAAAAAAABQABAAAAAAIACgDIAEgKIAEgMIACgGQAAgCgDgCQgBAAgBgBQgBAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAIAKgBIAJABQABAAABABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAABIgDAAQgDACgEALIgCAEIgIATQgKAZgFAIQgHAIgJAAQgEAAgEgDg");
	this.shape_11.setTransform(95.4,-15.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AALAdIgDgEIgDACQgHAFgHAAQgJAAgGgGQgFgEAAgJQAAgJAHgFQAHgGANABIAEABQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAADgDAAQgGAAgEADQgEADAAAFQAAAFAEADQADADAFAAQAFAAADgDQACgCAAgHIAAgWQAAgGgCgDQgCgCgEAAQgDgBgCACIgFAEIgCACQgDAEgEAAQgBAAAAAAQgBAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAgBAAgBQAAgFAHgEQAHgEALAAQAGAAAFACQAFACADADQACACAAAEIABANIAAASIABAGIACACIABAAQAEABAAACQAAADgEADQgEACgFAAQgDAAgDgDg");
	this.shape_12.setTransform(88.9,-17.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgaAlQgHgIAAgOQAAgOAIgJQAIgJAOAAIADAAIADACIABADQAAADgEAAIgBAAIgBAAQgIAAgDAGQgFAEAAAKQABAKAEAHQAEAGAHAAQAGAAADgDQAEgEgBgHIAAgRIAAgbIAAgGIgDgCIgCgBQgBAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAABgBQAAAAAAAAQAAgBAAAAQABAAAAgBIAGgDIAHgBIAGgBIADABIAAAEIAAADIAAAlIAAAZQAAAGABABIAFABQAAAAABABQABAAAAAAQABABAAAAQAAABAAAAQAAADgJADIgGABIgEABIgDgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAgDIAAgBIgBgBIgCACIgCACQgDADgDABQgDABgFAAQgLAAgHgIg");
	this.shape_13.setTransform(82.1,-18.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgKAsQgBgBAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABgBQAAAAABgBIACAAQAAAAAAgBQABAAAAAAQAAgBABAAQAAgBAAAAIAAgGIAAgFIAAgEIAAgHIAAgLIgBgEIgEgBQgEgBAAgCIACgCIAEgDIAJgDIAFgBIADABIABAEIAAAEIAAACIgBAPIAAAAIAAAQIAAAIIACADIACABQABAAABABQAAAAABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBABIgKABQgJAAgDgBgAgGgeQgDgCAAgDQAAgEADgCQACgCAEgBQADAAADACQADADAAAEQAAADgDACQgDACgDABQgEgBgCgCg");
	this.shape_14.setTransform(76.3,-18.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgKAsQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAgBIAEgCIABgEIAAgMIAAgKIAAgKIAAgFIAAgUIgCgFIgEgBQgEgBAAgDQAAAAAAAAQAAgBAAAAQABAAAAgBQAAAAAAAAIAGgDIAIgCIAFgBQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAAAIABAEIAAAFIgBArIABAVIABAFIADACQABABAAAAQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgLABQgIAAgEgBg");
	this.shape_15.setTransform(72.6,-18.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgWAXQgIgJAAgOQAAgMAJgKQAJgJANAAQANAAAIAJQAJAIAAAOQAAANgJAJQgJAKgNAAQgNAAgJgJgAgLgRQgDAFgBAIQAAALAGAIQAEAIAHAAQAGAAADgFQAEgFABgIQgBgLgEgIQgGgIgGAAQgGAAgEAFg");
	this.shape_16.setTransform(67.4,-17.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAOArQgBAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAAAQAAgDAEgCIADgBIABgEIAAgPIAAgJIAAgCIgDgBIgPgBIgMABIgFABIAAABIgBAFIAAAFIABAPIABAEIADABQAEACAAADQAAAAAAABQAAAAgBABQAAAAgBAAQgBABAAAAIgOABIgMgBQgBAAgBgBQgBAAAAAAQgBgBAAAAQAAgBAAAAQAAgDAEgCIACgBQACgBAAgIIABgZIgBgWQAAgKgBgBIgDgCQgEgBAAgDQAAAAAAgBQAAAAABgBQAAAAABAAQAAgBABAAQACgBALAAQALAAADABQABAAAAABQABAAAAAAQABABAAAAQAAABAAAAQAAADgEABIgDACIgBAEIgBASQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQACABAJAAIAEAAIANgBIAFgCIAAgBIAAgCIAAgCIAAgQQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAAAAAAAIgDgCQgEgBAAgDQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBABAAQADgBAKAAQALAAAEABQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAQAAADgDABIgEACQgBAAgBAJIAAAYIAAAXQABAJABABIAEACQADACAAADQAAAAAAABQAAAAgBABQAAAAgBAAQgBABAAAAIgOABIgMgBg");
	this.shape_17.setTransform(59.1,-18.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidayinspirationmobileleaderboard, new cjs.Rectangle(52.3,-27.7,114.2,18.5), null);


(lib.fillinboxmobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAJAsQgBgBgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQABgBABAAIACgBQAAAAAAAAQABgBAAAAQAAgBAAAAQABgBAAAAIAAgJQAAgUgCgEQgCgFgHAAQgCAAgDACQgDACgCACQgBADgBAFIAAAQIAAAIIACADIACABQABAAABABQAAAAABABQAAAAABABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQgBAAAAABIgLABQgKAAgDgBQAAgBgBAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQABgBAAAAIACgBIACgDIABgJIAAgKIAAgKIgBgaQAAgHgBgBIgEgCQgBAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIAHgDIAGgCIAFgBIADABIABAEIAAADIAAAYIAAADIAAACIABAAIABgBIACgDQADgDADgBIAHgCQAKAAAGAHQAFAHAAANIAAAFIAAALIAAAEIAAAEIACACIACABQAAAAABABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBABQgDABgKAAIgKgBg");
	this.shape.setTransform(34.5,-1.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgCAkIgGgDIgCgEIgBgNIAAggIgGAAIgCgBIAAgBIAAgCQAAgCAGgFIADgCIACgCQAGgFACgBIABABIABABIAAAMIAOAAIACABIAAABIAAACIAAACIgCABIgNAAIgBABIAAABIAAAdQAAAIABACQABABAAAAQABAAAAABQABAAAAAAQABAAABAAIAFgBIAFgBIABABIABACQABADgGADQgFADgHABIgFgCg");
	this.shape_1.setTransform(28.9,-1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgKArQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAQAAAAABgBQAAAAABgBQAAAAABAAIABgBQABAAAAgBQABAAAAAAQAAgBABAAQAAAAAAgBIAAgHIAAgEIAAgFIAAgGIAAgMIgCgDIgCgBQgEgBgBgDIACgCIAEgCIAJgDIAGgBIABABIABAEIAAAEIAAADIAAAOIAAABIgBAOIABAJIACADIADABQAAAAABABQAAAAABAAQAAABAAAAQABABAAABQAAAAgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgMABQgIAAgDgBgAgHgeQgCgCAAgDQAAgDACgDQAEgCADAAQADAAAEACQACACAAADQAAADgDADQgDACgDAAQgEAAgDgCg");
	this.shape_2.setTransform(24.9,-1.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AADAHIgGgTQgDgIgDgCIgCAAQgDgCgBgDQAAAAABgBQAAAAAAAAQABgBAAAAQABAAAAAAQAEgBAJAAIAKABQABAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAACIgBABIgCACQgBAAAAAAQgBAAAAABQAAAAAAAAQAAABAAAAIABAEIAEANIAGAKIACADIACgCIADgEIAHgPIACgIIgBgCIgBgBIgCgCQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAIAKgBIAJABQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAQAAABAAABQAAAAgBABQAAAAgBAAQgBABgBAAIgCABQgDABgFANIgBADIgCAFQgPAfgDABQgEAAgMgZgAgjADIgBgDIgFgKQgDgKgEgCIgBAAQgEgCAAgDQAAAAAAgBQAAAAABAAQAAgBABAAQABAAAAAAQADgBALAAIALABQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAACIgBABIgCACQgBAAAAAAQgBAAAAABQAAAAAAAAQAAABAAAAIABAFIAEAMIAGAKQAAABAAABQABAAAAABQAAAAAAAAQABAAAAAAQACAAABgDIADgFIABgCIACAAIACAAIABADIgCAFIgJASQgCAFgCABQgFAAgMgdg");
	this.shape_3.setTransform(18.3,-0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAGAdQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAIACgCIgCgFIgKgQIgKgPIgGgFIgEgCQAAAAgBgBQAAAAgBAAQAAgBAAAAQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIALgBIAMABQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAAAIgCADQAAABAGAKIAAAAIADgCIAFgJIgCgDQgBAAAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQABAAABAAIAJgBIAIABQAAAAABAAQABAAAAABQAAAAABABQAAAAAAAAQAAADgFACIgDABQgDABgDAEIgIANIAKAQIAGAGIAEADQABAAABAAQAAAAABABQAAAAABABQAAAAAAABQAAACgEABIgLABIgLgBgAgcAdQgBAAAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQAAgDAFgBIADgBIAFgFIAFgIIACgBIACAAIACAAIABACIgBAEIgFAHQAAABAAAAQAAAAAAAAQABABAAAAQABAAAAABQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAAAQgBABAAAAQgEABgGAAIgIgBg");
	this.shape_4.setTransform(6.9,-0.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgWAXQgIgJAAgOQAAgMAJgKQAJgJANAAQANAAAJAJQAIAIAAAOQAAANgJAJQgJAKgNAAQgNAAgJgJgAgLgRQgEAFABAIQAAALAEAIQAGAIAGAAQAGAAAEgFQADgFAAgIQAAgLgEgIQgGgIgGAAQgGAAgEAFg");
	this.shape_5.setTransform(0.5,-0.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgIAsQgFgCgDgCIgEACIgDABIgDAAIgCgBIAAgBQACgCACgGIABgTIAAgNIAAgNIgBgPQgBgEgBgBIgDgBQgEgBAAgCIABgDIAGgCIAHgCIAGgBIADABIABADIAAADIgBASIAAAaIAAAQQAAAJAEADQACADAHAAQAHAAAEgHQAFgGgBgLQAAgKgEgFQgEgGgHAAIgCAAIgBAAQgEAAAAgEQAAgDAEgBQADgCAGAAQAMAAAGAIQAHAIAAAMQAAAQgJAJQgIAJgOAAQgGAAgFgBg");
	this.shape_6.setTransform(-6.8,-1.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAIAeQAAAAgBAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQABAAAAAAIADgBIACgEIAAgJQAAgTgCgEQgDgFgGAAQgDAAgDACQgDACgBADIgCAHIgBAQIABAIQAAAAAAABQAAAAABABQAAAAAAAAQAAABABAAIACABQABAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAIgLABQgJAAgDgBQgBAAgBAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABgBIABAAQABAAAAgBQABAAAAAAQAAgBAAAAQABgBAAAAIAAgHIAAgEIAAgFIAAgFIAAgNIgCgDIgDgBQgEgBAAgDIACgCIADgCIAJgDIAGgBIADABIABADIAAAEIAAABIAAAAIABAAIAAgBIABgBIABgBQAHgGAHAAQAEAAAEACIAHAFIAEAIIABAOIAAAIIAAAEIAAADIABAGIACADIACAAQABABAAAAQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBABQAAAAgBAAIgMABQgJAAgDgBg");
	this.shape_7.setTransform(-13.7,-0.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgMArQgBAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAgBQAAgCAFgCIACgBQACgBAAgHIAAgaIAAgXQAAgJgCgBIgDgCQgDgCgBgCQAAgBABAAQAAAAAAgBQABAAAAAAQABgBABAAQACgBAKAAQALAAADABQAAAAABABQAAAAABAAQAAABAAAAQABAAAAABQAAADgFABIgCABQgBACgBAFIAAAUIAAAcQAAAMABABIAEABQADACABACQAAABgBABQAAAAAAABQgBAAAAAAQgBABgBAAIgNABIgMgBg");
	this.shape_8.setTransform(-19.3,-1.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgSAeQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAIACgBIACgDIABgHIAAgEIAAgFIAAgDIgBgOIgCgEIgDgBQAAgBgBAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIABgCIADgCIAJgDIAGgBQACAAABAIIAAACIAAAAQADgFADgDQAEgCAEAAQAEAAACACQADADAAAEQAAAEgCADQgCACgEAAIgCAAIgDgCIgCgCQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAQgEAAgCAGQgBAGAAARIAAAIQABABAAAAQAAABAAAAQAAABABAAQAAABABAAIACAAQAEACgBACQAAABAAAAQAAABAAAAQgBAAAAABQgBAAAAAAIgLABQgKAAgDgBg");
	this.shape_9.setTransform(-26.7,-0.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AANAfIgBgDIAAgEIgCABIgBABQgDADgDABQgDACgFAAQgEAAgEgCQgEgCgDgDQgDgEgBgEIgBgRIAAgFIAAgEIAAgBIgBgHIgDgCIgCAAQgBgBgBAAQAAAAgBgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABgBIAFgCIAIgCIAHgBQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIABADIAAACIgBAYQAAALADAFQACAEAGAAQAHABADgHQADgGAAgOIAAgEIgBgHIgDgCIgCAAQgBgBgBAAQAAAAgBgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAAAgBQAAAAABAAQABgCAEgBIAIgCIAHgBIACABIABAEIAAADIgBAZIAAAKIABAEQAAADADABIABAAQABABABAAQAAAAABABQAAAAABABQAAAAAAABIgBACIgEACIgJADIgGABIgDgBg");
	this.shape_10.setTransform(-32.9,-0.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgVAXQgJgJAAgOQAAgMAJgKQAJgJANAAQANAAAJAJQAIAIAAAOQAAANgJAJQgKAKgMAAQgNAAgIgJgAgLgRQgEAFAAAIQABALAEAIQAFAIAHAAQAGAAADgFQAFgFAAgIQAAgLgGgIQgFgIgGAAQgGAAgEAFg");
	this.shape_11.setTransform(-39.9,-0.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgMArQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBQAAgCADgCIADgBQACgBAAgZIAAgGIgHgLIgLgSQgEgGgCgBIgDgBQgEgBAAgCQAAgBAAgBQAAAAAAgBQABAAAAAAQABgBABAAQADgBAMAAQALAAADABQABAAABABQAAAAABAAQAAABAAAAQAAABAAABQAAACgFABIgCACIAAABIACAGIAMATIAKgQIADgHIAAgDIgEgCIgDgBIgBgCQAAgBAAgBQAAAAAAgBQABAAAAAAQABgBAAAAQADgBAKAAQAKAAADABQAAAAABABQAAAAABAAQAAABAAAAQAAABAAABQAAAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgFACQgDACgFAKIgPAWIAAALQAAAVACABIADABQADACAAACQAAABAAABQAAAAAAABQgBAAAAAAQgBABgBAAIgNABIgMgBg");
	this.shape_12.setTransform(-47.3,-1.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgKAsQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAIAEgCIABgEIABgMIAAgKIgBgKIAAgFIAAgUIgCgFIgEgBQgEgBAAgDQAAAAAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIAFgDIAIgCIAFgBIADABIABAEIgBAFIAAArIAAAVIACAFIADACQABAAAAABQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAABgBAAQAAAAgBABIgLABQgJAAgDgBg");
	this.shape_13.setTransform(-56.3,-1.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgKAsQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAIAEgCIABgEIAAgMIAAgKIAAgKIAAgFIAAgUIgCgFIgEgBQgEgBAAgDQAAAAAAAAQAAgBAAAAQABAAAAgBQAAAAAAAAIAGgDIAIgCIAFgBIADABIABAEIAAAFIgBArIABAVIABAFIADACQABAAAAABQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAABgBAAQAAAAgBABIgLABQgIAAgEgBg");
	this.shape_14.setTransform(-59.7,-1.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgKArQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAQAAAAABgBQAAAAABgBQAAAAABAAIABgBQABAAAAgBQABAAAAAAQAAgBABAAQAAAAAAgBIABgHIAAgEIAAgFIAAgGIgBgMIgCgDIgDgBQgDgBAAgDIABgCIADgCIAKgDIAFgBIACABIABAEIAAAEIAAADIAAAOIAAABIgBAOIABAJIACADIADABQAAAAABABQAAAAABAAQAAABAAAAQAAABAAABQAAAAAAAAQAAABAAAAQgBABAAAAQgBAAAAAAIgLABQgJAAgDgBgAgGgeQgDgCAAgDQAAgDADgDQADgCADAAQAEAAACACQADACAAADQAAADgDADQgDACgDAAQgEAAgCgCg");
	this.shape_15.setTransform(-63.1,-1.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgeAsQgEgBABgDQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABgBIADgCQACgBAAgJIABgYIgBgWQAAgJgCgBIgDgCQgEgCABgCQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAQADgBAKAAIAlAAIAGgBIAEgBIABABIABABIACAGIABAHIgBAFQAAAAAAAAQAAABgBAAQAAAAgBAAQAAAAAAAAQgCAAgDgEIgCgDQgBgCgDgBIgHgBIgIAAIgIABQgBAAAAAAQgBAAgBABQAAAAAAAAQgBAAAAABIgCAFIAAAMIAAAFIAAADIADABIAJAAQAEAAADgBQABgCABgEIAAgBQABgGADAAQABAAABAAQAAABABAAQAAAAAAABQABAAAAABQABAEAAALQAAALgBADQAAABgBABQAAAAAAABQgBAAAAABQgBAAgBAAQgDAAgBgHIAAgBQgBgEgBgBIgHgBIgJAAIgDABIAAAFIAAAEIAAARIACAFIADABQADACAAACQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBABIgNABQgKAAgDgBg");
	this.shape_16.setTransform(-68.4,-1.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.fillinboxmobileleaderboard, new cjs.Rectangle(-74.3,-11,114.6,18.5), null);


(lib.diytipsmobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgEAgIgGgBIgCABIgCAAIgBAAIgBgBQgCgCgCgFQgCgEAAgFIABgDQAAAAABgBQAAAAAAAAQAAAAABAAQAAAAABAAQACAAADAEIADAEQABACADACIAHABQADAAADgBQACgDABgDQAAgGgKgEIgEgCQgJgFgDgDQgDgEAAgFQgBgJAGgFQAGgEAIAAIADAAIAFAAIADAAIABgBQADAAAEAFQACAFAAAFIgBAEIgCAAIgDAAIgEgFQgCgEgCgBQgCgBgEAAQgDAAgCACQgCABAAADQAAAEACABQACADAHAEIABAAQARAIAAAKQAAAIgGAFQgHAGgKAAg");
	this.shape.setTransform(142.5,-17.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdAqQgDgBAAgDQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAABAAIACgCQACgBAAgFIABgUIAAgJIgBgVQAAgFgCgBIgCgBQgBAAgBAAQgBgBAAAAQgBgBAAAAQAAgBAAAAIABgDIAEgBIAIgDIAGgBIADABIABADIAAADIAAABIAAAAIACgBIACgCIAHgEIAHgCQALAAAHAJQAIAIAAANQAAAOgIAJQgJAKgMAAQgFAAgBgCQgBAAAAgBQgBAAAAAAQAAgBAAgBQAAAAAAgBIABgCIACgBIABAAIACABQAHAAAEgGQAEgGAAgIQAAgLgEgGQgEgGgIAAQgFAAgEADQgDAEAAAJIAAAmIAAAGIABADIADACIADAAIACACIAAABQAAADgEABIgMABIgMgBg");
	this.shape_1.setTransform(136,-16.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgKArQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAQAAAAABgBQAAAAABgBQAAAAABgBIABAAQABAAAAgBQABAAAAAAQAAgBABAAQAAAAAAgBIAAgHIAAgDIAAgGIAAgGIAAgMIgCgDIgCgBQgFgBAAgDIACgCIAEgCIAJgDIAGgBIACABIAAAEIAAAEIAAADIAAAOIAAAAIAAAPIAAAJIACADIACABQABAAABABQAAAAABAAQAAABAAAAQABABAAABQAAAAgBAAQAAABAAAAQgBABAAAAQgBAAgBAAIgLABQgIAAgDgBgAgHgeQgCgCAAgDQAAgEACgCQADgDAEAAQAEABADACQACACAAADQAAAEgDACQgDADgDgBQgEABgDgDg");
	this.shape_2.setTransform(130.6,-18.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgMArQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBQABgDADgBIAEgCIABgLIAAgcIAAgQIgBgKIAAgCIgEAAIgDAAIgGABIgFACIgBAEIgCAFIgCACIgCAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAgBgBAAIAAgGQAAgIABgFQACgEADgBIABABIAMABIAjAAIAMgBIABgBQADABACAEQACAFgBAIIAAAGQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAIgCAAIgCgCIgCgFIgCgEIgDgCIgHgBIgCAAIgEAAQAAAAgBAAQAAAAAAABQAAAAAAAAQAAABAAAAIgBAKIAAAQIAAAcIABALIAEACQADABABADQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAIgNABIgMgBg");
	this.shape_3.setTransform(124.7,-18.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgMArQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBQAAgCADgBIADgCQACgBAAgZIAAgGIgHgLIgLgSQgEgFgCgCIgDgBQgEgBAAgCQAAgBAAgBQAAAAABgBQAAAAAAAAQABgBABAAQADgBAMAAQALAAADABQABAAABABQAAAAAAAAQABABAAAAQAAABAAABQAAACgFABIgCACIAAABIACAGIAMATIAKgQIADgHIAAgDIgEgCIgDgBIgBgCQAAgBAAgBQAAAAAAgBQABAAAAAAQABgBAAAAQADgBAKAAQAKAAADABQAAAAABABQAAAAABAAQAAABAAAAQAAABAAABQAAAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgFACQgDADgFAIIgPAXIAAALQAAAVACABIADACQADABAAACQAAABAAABQAAAAgBABQAAAAAAAAQgBABgBAAIgNABIgMgBg");
	this.shape_4.setTransform(113.1,-18.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgMArQgBAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBQAAgCADgBIADgCQACgBAAgHIABgaIgBgXQgBgJgBgBIgDgCQgDgCAAgCQAAAAAAgBQAAAAAAgBQABAAAAAAQABgBABAAQACgBAKAAQALAAADABQAAAAABABQAAAAABAAQAAABAAAAQAAABAAAAQAAADgDABIgDABQgCABAAAHIgBATIABAcQAAAMABABIAEACQAEABgBACQAAABAAABQAAAAAAABQgBAAAAAAQgBABgBAAIgNABIgMgBg");
	this.shape_5.setTransform(107,-18.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgMAsIgIAAIgFAAIgFAAIgKgBQAAAAgBgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABAAQAAgBABAAIAEgCQABgCAAgJIABgXIgBgWQAAgJgBgCIgEgCQgDgBAAgDQAAAAAAgBQAAAAAAAAQABgBAAAAQABAAAAgBIAKgBIAGAAIAGAAIAIAAIAHAAQAWAAAMAMQAMALAAAVQAAAVgMALQgNALgXAAgAgMgiQgBABgBAAQAAAAgBABQAAAAAAAAQgBABAAAAIgBAJIgBATIABAWIABAMQABACAEABIAJABQAOAAAHgIQAHgJAAgRQAAgRgIgJQgIgKgPAAIgHABg");
	this.shape_6.setTransform(100.1,-18.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.diytipsmobileleaderboard, new cjs.Rectangle(93.4,-27.8,54.1,18.5), null);


(lib.ctarollovervideomobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("An/BpIAAjRIP/AAIAADRg");
	this.shape.setTransform(0,0,1.112,0.832);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarollovervideomobileleaderboard, new cjs.Rectangle(-56.9,-8.7,113.8,17.5), null);


(lib.ctamobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AoEBjIAAjFIQIAAIAADFg");
	this.shape.setTransform(-19.6,-1.1,0.631,0.701);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctamobileleaderboard, new cjs.Rectangle(-52.2,-8,65.2,13.9), null);


(lib.blackwideskyscraper = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRBA2FMAAAhsJMAiDAAAMAAABsJg");
	this.shape.setTransform(0,0,0.753,0.867);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackwideskyscraper, new cjs.Rectangle(-82.1,-300,164.3,600.1), null);


(lib.ctarollovermobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(2));

	// Layer 1
	this.instance = new lib.ctarollovervideomobileleaderboard();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-56.9,-8.7,113.8,17.5);


// stage content:
(lib.mobileleaderboardkalebackgroundslidetransitionfillinboxsomethingdelicious = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_28 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_168 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(28).call(this.frame_28).wait(140).call(this.frame_168).wait(5));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(160.7,25.5,1.558,0.078,0,0,0,0.2,0.7);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(173));

	// fade-from-white
	this.instance = new lib.blackwideskyscraper();
	this.instance.parent = this;
	this.instance.setTransform(161,25.5,1.954,0.085,0,0,0,0.3,0);
	this.instance.filters = [new cjs.ColorFilter(0, 0, 0, 1, 255, 255, 255, 0)];
	this.instance.cache(-84,-302,168,604);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:0.1,scaleX:1.95,scaleY:0.08,x:160.1,y:25,alpha:0},9).wait(164));

	// white-logo
	this.instance_1 = new lib.whitelogo();
	this.instance_1.parent = this;
	this.instance_1.setTransform(281.9,23.4);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({scaleX:0.02,scaleY:0.02},0).to({scaleX:1.08,scaleY:1.08,alpha:1},6,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},7,cjs.Ease.get(1)).wait(151));

	// fill-mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AxFCuIAAkcMAkUAAAIAAEcg");
	mask.setTransform(123.1,17.4);

	// fill-your-inbox-with
	this.instance_2 = new lib.fillinboxmobileleaderboard();
	this.instance_2.parent = this;
	this.instance_2.setTransform(76.4,14.6);
	this.instance_2.alpha = 0;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(16).to({x:-103.1,y:15.8},0).to({x:96.4,y:14.6,alpha:1},10,cjs.Ease.get(1)).to({x:86.4},6,cjs.Ease.get(1)).wait(141));

	// party-ready-mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("AuPCTIAAkcMAkUAAAIAAEcg");
	mask_1.setTransform(141.3,14.7);

	// party-ready-recipes
	this.instance_3 = new lib.partyreadyrecipesmobileleaderboard();
	this.instance_3.parent = this;
	this.instance_3.setTransform(79.2,31.4);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(16).to({x:-117.8,y:32.8},0).to({x:89.2,y:31.4,alpha:1},10,cjs.Ease.get(1)).to({x:79.2},6,cjs.Ease.get(1)).wait(44).to({alpha:0},5).to({_off:true},89).wait(3));

	// diy-tips-mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("AuPCYIAAkdMAkUAAAIAAEdg");
	mask_2.setTransform(141.3,15.2);

	// diy-tips
	this.instance_4 = new lib.diytipsmobileleaderboard();
	this.instance_4.parent = this;
	this.instance_4.setTransform(39,31.4);
	this.instance_4.alpha = 0;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(76).to({x:32.5},0).to({alpha:1},10,cjs.Ease.get(1)).wait(30).to({alpha:0},5).to({_off:true},49).wait(3));

	// holiday-mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("AuPCVIAAkcMAkUAAAIAAEcg");
	mask_3.setTransform(141.3,14.9);

	// holiday-inspiration
	this.instance_5 = new lib.holidayinspirationmobileleaderboard();
	this.instance_5.parent = this;
	this.instance_5.setTransform(73.9,31.4);
	this.instance_5.alpha = 0;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(116).to({alpha:1},10,cjs.Ease.get(1)).wait(30).to({alpha:0},5).to({_off:true},9).wait(3));

	// delicious-mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	mask_4.graphics.p("At7CZIAAkcMAkUAAAIAAEcg");
	mask_4.setTransform(143.3,15.4);

	// something-delicious
	this.instance_6 = new lib.somethingdeliciousmobileleaderboard();
	this.instance_6.parent = this;
	this.instance_6.setTransform(79.2,31.4);
	this.instance_6.alpha = 0;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(156).to({alpha:1},10).to({_off:true},4).wait(3));

	// sign-up-mask (mask)
	var mask_5 = new cjs.Shape();
	mask_5._off = true;
	mask_5.graphics.p("Av7D6IAAkcMAiFAAAIAAEcg");
	mask_5.setTransform(116.2,25);

	// sign-up
	this.instance_7 = new lib.signupmobileleaderboard();
	this.instance_7.parent = this;
	this.instance_7.setTransform(207.6,24.3);
	this.instance_7.alpha = 0;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_5;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(28).to({x:33.7},0).to({x:229.5,alpha:1},10,cjs.Ease.get(1)).to({x:219.5},8,cjs.Ease.get(1)).to({_off:true},125).wait(2));

	// rollover-mask (mask)
	var mask_6 = new cjs.Shape();
	mask_6._off = true;
	mask_6.graphics.p("AxBDrIAAmoMAkUAAAIAAGog");
	mask_6.setTransform(123.5,23.5);

	// cta-rollover
	this.cta_rollover = new lib.ctarollovermobileleaderboard();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(71.3,32.5);

	var maskedShapeInstanceList = [this.cta_rollover];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_6;
	}

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(28).to({x:-79},0).to({x:81.3},10,cjs.Ease.get(1)).to({x:71.3},8,cjs.Ease.get(1)).to({_off:true},125).wait(2));

	// cta-mask (mask)
	var mask_7 = new cjs.Shape();
	mask_7._off = true;
	mask_7.graphics.p("AxBDrIAAmoMAkUAAAIAAGog");
	mask_7.setTransform(123.5,23.5);

	// cta-rectangle
	this.instance_8 = new lib.ctamobileleaderboard();
	this.instance_8.parent = this;
	this.instance_8.setTransform(105.5,33.9,1.745,1.269);
	this.instance_8.alpha = 0;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_7;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(28).to({x:-79},0).to({x:115.5,alpha:1},10,cjs.Ease.get(1)).to({x:105.5},8,cjs.Ease.get(1)).to({_off:true},125).wait(2));

	// kale-background
	this.instance_9 = new lib.kalebackground();
	this.instance_9.parent = this;
	this.instance_9.setTransform(162.3,28.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({_off:true},171).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(153.1,18.7,338.5,68.4);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 320,
	height: 50,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;